//! `yew-core`: the Rust core of YEW ("Your Electronic Wallet"), a transparent-only mobile
//! wallet for YEC and Ycash Yellowback (YED).
//!
//! Every wire byte, script byte, key and signature of the wallet lives here; the Flutter app is a
//! view over [`api`]. Plan: `docs/plans/yellowback-wallet-plan.md` (workspace), §3.
//! Each module names its translation source (plan §3.6). Phase W1: keys, script, tx, net (T0),
//! store, coins, sync (YEC), build::yec_send, gate (YEC path), wallet. Phase W2: payload,
//! coinselect, net::yellowback, the TOKEN / PENDING_TOKEN classes, build::yed_transfer, the
//! full gate (local classes + the node's `ValidateRawTransaction`), history labels, balances.

pub mod api;
pub mod build;
pub mod bundle;
pub mod coins;
pub mod coinselect;
/// Generated by `scripts/gen-bridge.sh` (flutter_rust_bridge 2.13.0); do not edit.
mod frb_generated;
pub mod gate;
pub mod keys;
pub mod net;
pub mod params;
pub mod payload;
pub mod script;
pub mod store;
pub mod sync;
pub mod tx;
pub mod wallet;

/// Crate version, as pinned in the workspace `Cargo.toml`.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

#[cfg(test)]
mod tests {
    #[test]
    fn version_is_set() {
        assert!(!super::VERSION.is_empty());
    }
}
