// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connect`, `ensure_conn`, `format_yec`, `from_network`, `gate_message`, `hex_or_empty`, `history_item`, `locked`, `merge_shielded`, `mint_status_of`, `new`, `open_wallet`, `params_dir_of`, `params_status_of`, `parse_server`, `parse_txid`, `row_status`, `runtime`, `shielded_pair`, `store_err`, `sync_shielded`, `sync`, `synced_tip`, `to_network`, `vault_summary`, `wallet_id`, `with_open_async`, `with_open`, `yec_preview_of`, `yellowback_status`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Conn`, `Open`, `Preview`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// The core's version.
String coreVersion() => RustLib.instance.api.crateApiCoreVersion();

/// A fresh BIP39 English mnemonic of 12 or 24 words (the app stores it in the keystore).
String generateSeedWords({required int words}) =>
    RustLib.instance.api.crateApiGenerateSeedWords(words: words);

/// Check a mnemonic without opening anything.
void checkSeedWords({required String seedWords}) =>
    RustLib.instance.api.crateApiCheckSeedWords(seedWords: seedWords);

/// Parse an address for `network` (the Send screen's field check).
AddressCheck validateAddress({
  required NetworkId network,
  required String address,
}) => RustLib.instance.api.crateApiValidateAddress(
  network: network,
  address: address,
);

/// The default endpoints the app offers for `network`, in order of preference (possibly none).
List<DefaultEndpoint> defaultServers({required NetworkId network}) =>
    RustLib.instance.api.crateApiDefaultServers(network: network);

/// Probe a server before any wallet is open (Onboarding's default birthday, Settings' server
/// check). Contract rule 1: an unknown `rpcversion` is an error. `ca_pem` pins a certificate
/// (PEM) as the only trust anchor (audit G-4).
Future<ServerProbe> probeServer({
  required String server,
  required bool plain,
  String? caPem,
  required NetworkId network,
}) => RustLib.instance.api.crateApiProbeServer(
  server: server,
  plain: plain,
  caPem: caPem,
  network: network,
);

/// Create (or restore) a wallet and open it. `seed_words` `None` generates a 12-word mnemonic
/// and returns it once in [`Created::seed_words`]. `birthday` `None` = from the first block
/// (pass the server's tip for a new seed). `data_dir` is the app's private directory.
Future<Created> createWallet({
  String? seedWords,
  required String passphrase,
  PlatformInt64? birthday,
  required NetworkId network,
  required String server,
  required bool plain,
  String? caPem,
  required String dataDir,
}) => RustLib.instance.api.crateApiCreateWallet(
  seedWords: seedWords,
  passphrase: passphrase,
  birthday: birthday,
  network: network,
  server: server,
  plain: plain,
  caPem: caPem,
  dataDir: dataDir,
);

/// Open an existing wallet with its seed (from the keystore). Returns the wallet id.
Future<String> unlock({
  required String seedWords,
  required String passphrase,
  required NetworkId network,
  required String server,
  required bool plain,
  String? caPem,
  required String dataDir,
}) => RustLib.instance.api.crateApiUnlock(
  seedWords: seedWords,
  passphrase: passphrase,
  network: network,
  server: server,
  plain: plain,
  caPem: caPem,
  dataDir: dataDir,
);

/// Drop the wallet handle, its derived keys, its connection and any preview.
Future<void> lock() => RustLib.instance.api.crateApiLock();

/// Is a wallet open?
bool isUnlocked() => RustLib.instance.api.crateApiIsUnlocked();

/// Change the server of the open wallet (Settings). The next call reconnects.
Future<void> setServer({
  required String server,
  required bool plain,
  String? caPem,
}) => RustLib.instance.api.crateApiSetServer(
  server: server,
  plain: plain,
  caPem: caPem,
);

/// Server info, Yellowback info, tip, sync height (connects if needed).
Future<Status> status() => RustLib.instance.api.crateApiStatus();

/// The balances from the store (no network).
Future<Balances> balances() => RustLib.instance.api.crateApiBalances();

/// The receive address of `kind`. Transparent kinds: the first unused external address
/// (`fresh` marks the current one used first). Shielded: the address last handed out by
/// [`new_shielded_address`], or the default `ys1…` address (`fresh` is ignored; diversified
/// addresses all reach the same account).
Future<AddressPair> receiveAddress({
  required ReceiveKind kind,
  required bool fresh,
}) => RustLib.instance.api.crateApiReceiveAddress(kind: kind, fresh: fresh);

/// A new diversified `ys1…` address of the same private account (Receive → "new address"):
/// unlinkable to the others on chain, received into the same balance. Remembered, so
/// [`receive_address`] with [`ReceiveKind::Shielded`] shows it until the next one.
Future<AddressPair> newShieldedAddress() =>
    RustLib.instance.api.crateApiNewShieldedAddress();

/// Every address of the wallet (Settings → export private key picks one).
Future<List<AddressPair>> addresses() =>
    RustLib.instance.api.crateApiAddresses();

/// One page of history (pending first, then newest first). `page_size` 0 = 50.
Future<HistoryPage> history({required int page, required int pageSize}) =>
    RustLib.instance.api.crateApiHistory(page: page, pageSize: pageSize);

/// Plan a YEC send (after a sync of both pools), funded **privacy first**
/// (`build::yec_private`): a `ys1…` recipient (optionally with a text `memo` of at most 512
/// bytes) from private notes; a transparent recipient from private notes when they cover it
/// (`reveals_shielded` set: the amber line), else from transparent YEC exactly as before.
/// A transparent preview is signed already; a private one is proved and signed at confirm.
/// Nothing is broadcast.
Future<YecPreview> sendYecPreview({
  required String to,
  required PlatformInt64 zat,
  required bool sendEverything,
  String? memo,
}) => RustLib.instance.api.crateApiSendYecPreview(
  to: to,
  zat: zat,
  sendEverything: sendEverything,
  memo: memo,
);

/// Plan a move of `amount_zat` (`None`: everything that direction can move, less the fee)
/// between the wallet's own public and private balances, after a sync of both (yew-shielded
/// plan S4, `build::yec_move`). To private spends plain public YEC only, never the fee reserve
/// or anything YED. The preview is the send preview (`to` is the wallet's own address); confirm
/// with [`move_confirm`]. Both directions prove at confirm (`params_needed`).
Future<YecPreview> movePreview({
  required MoveDirection direction,
  PlatformInt64? amountZat,
}) => RustLib.instance.api.crateApiMovePreview(
  direction: direction,
  amountZat: amountZat,
);

/// Broadcast a [`move_preview`] (the same gate and bookkeeping as [`send_yec_confirm`]).
Future<SendResult> moveConfirm({required String previewId}) =>
    RustLib.instance.api.crateApiMoveConfirm(previewId: previewId);

/// Broadcast a YEC preview through the gate (D-W-5). A private send is proved and signed
/// here (seconds), with the proving parameters verified first ([`ErrorKind::ParamsMissing`]
/// when they are not downloaded: the preview stays valid, download, then confirm again).
Future<SendResult> sendYecConfirm({required String previewId}) =>
    RustLib.instance.api.crateApiSendYecConfirm(previewId: previewId);

/// Where the proving parameters stand on this device (no network).
Future<ParamsStatus> paramsStatus() =>
    RustLib.instance.api.crateApiParamsStatus();

/// Download the Sapling proving parameters from `base_url` (`https://host/dir/`; S0-2: the
/// owner's host; `file://` or a loopback `http://` for tests) into the app's data directory,
/// each file verified against its pinned SHA-256 before it is kept. Progress on `sink`, ending
/// with a `finished` event ([`params_status`] then says `ready`); the wallet stays usable
/// meanwhile (the download does not hold the wallet).
Stream<ParamsProgress> downloadParams({required String baseUrl}) =>
    RustLib.instance.api.crateApiDownloadParams(baseUrl: baseUrl);

/// Build and sign a YED transfer (after a sync) and dry-run it on the node. Nothing is
/// broadcast. With too little YEC for the fee the error is [`ErrorKind::NeedYecForFees`].
Future<YedPreview> sendYedPreview({required List<Recipient> recipients}) =>
    RustLib.instance.api.crateApiSendYedPreview(recipients: recipients);

/// Broadcast a YED preview through the gate (D-W-5): both layers again on the same bytes.
Future<SendResult> sendYedConfirm({required String previewId}) =>
    RustLib.instance.api.crateApiSendYedConfirm(previewId: previewId);

/// Export the WIF of an own address (D-W-11). The app shows the warning: YEC **and** YED on
/// this address move with the key.
Future<WifExport> exportWif({required String address}) =>
    RustLib.instance.api.crateApiExportWif(address: address);

/// Import a WIF (from YecWallet / `dumpprivkey`) as a key outside the HD tree (D-W-11).
/// `birthday` (the height to rescan from) lowers the wallet's scan floor so the next sync
/// finds the key's history. The key is not covered by the seed backup.
Future<AddressPair> importWif({required String wif, PlatformInt64? birthday}) =>
    RustLib.instance.api.crateApiImportWif(wif: wif, birthday: birthday);

/// Sync now, reporting progress on `sink` (Dart: a `Stream<SyncEvent>`), ending with `Done`
/// or `Failed`: the transparent sync (addresses, YED) and then the private (Sapling) scan, as
/// one progress (`percent`). A failed private sync does not fail the call: `Done` carries it
/// in `shielded_message` (transparent YEC and YED are synced either way). The returned error
/// mirrors the `Failed` event.
Stream<SyncEvent> syncNow() => RustLib.instance.api.crateApiSyncNow();

/// The mint estimate (after a sync): collateral, fees, payee, heights, term class, attestor
/// seqs, each checked against the network's rules (audit G-1, G-2). Nothing is signed. An
/// amount outside `[MIN_MINT, MAX_MINT]` is [`ErrorKind::Input`] (audit G-9).
Future<MintEstimate> mintEstimate({
  required PlatformInt64 cents,
  required int lockBlocks,
}) => RustLib.instance.api.crateApiMintEstimate(
  cents: cents,
  lockBlocks: lockBlocks,
);

/// Start a mint (after a sync): verify the bundle, fund the carrier through the gate, record
/// the row. `confirmed` is the estimate the user confirmed: a server answer that differs in
/// collateral, fee, payee or class is refused (`terms-changed`, audit G-2). Returns the row
/// (`CARRIER_SENT`); [`mint_finish`] sends the MINT once a sync has seen the carrier confirm.
Future<MintStatus> mintStart({
  required PlatformInt64 cents,
  required int lockBlocks,
  required MintTerms confirmed,
}) => RustLib.instance.api.crateApiMintStart(
  cents: cents,
  lockBlocks: lockBlocks,
  confirmed: confirmed,
);

/// One row of the two-step table (no network; heights judged at the last synced height).
Future<MintStatus> mintStatus({required PlatformInt64 mintId}) =>
    RustLib.instance.api.crateApiMintStatus(mintId: mintId);

/// Every two-step row (mints and claims), oldest first (no network).
Future<List<MintStatus>> mints() => RustLib.instance.api.crateApiMints();

/// Send the MINT (or, for a claim row, the CLAIM) over the confirmed carrier (after a sync;
/// both gate layers). The row must be `CARRIER_CONFIRMED` with the window open; a lapsed
/// row is refused with `carrier-lapsed`. Returns the row (`MAIN_SENT`).
Future<MintStatus> mintFinish({required PlatformInt64 mintId}) =>
    RustLib.instance.api.crateApiMintFinish(mintId: mintId);

/// Sweep the carrier of a `LAPSED` row (`CARRIER_VALUE − fee` back to the wallet; after a
/// sync; both gate layers). Returns the row (`SWEEP_SENT`).
Future<MintStatus> mintSweep({required PlatformInt64 mintId}) =>
    RustLib.instance.api.crateApiMintSweep(mintId: mintId);

/// The vaults this wallet owns, as the last sync left them (no network).
Future<List<VaultSummary>> vaults() => RustLib.instance.api.crateApiVaults();

/// Build and sign the REDEEM of an own `ACTIVE` vault at or past `lockHeight` (burning its
/// debt from the wallet's YED), or the release of a `VOID` one, after a sync. Nothing is
/// broadcast: the preview shows the collateral returned, the enforcement fee and its payee
/// (FEE-1, checked locally) and the burn before the slider (audit G-2).
Future<RedeemPreview> redeemPreview({required String vaultTxid}) =>
    RustLib.instance.api.crateApiRedeemPreview(vaultTxid: vaultTxid);

/// Broadcast a redeem preview through both gate layers (the planned burn known to the
/// remote layer).
Future<RedeemResult> redeemConfirm({required String previewId}) =>
    RustLib.instance.api.crateApiRedeemConfirm(previewId: previewId);

/// `ListClaimable` at the node's tip (connects; the liquidator persona).
Future<List<ClaimableItem>> claimable() =>
    RustLib.instance.api.crateApiClaimable();

/// Start a claim of another wallet's claimable vault (after a sync): the bundle, the carrier
/// through the gate, a row of kind `claim`. Returns the row; [`mint_finish`] sends the CLAIM
/// once the carrier is confirmed.
Future<MintStatus> claim({required String vaultTxid}) =>
    RustLib.instance.api.crateApiClaim(vaultTxid: vaultTxid);

/// [`validate_address`].
class AddressCheck {
  /// Parses for the network.
  final bool valid;

  /// `p2pkh` / `p2sh`, `sapling` for a private address (`ys1…` / `ytestsapling1…` /
  /// `yregtestsapling1…`), empty when invalid.
  final String kind;

  /// The `ye…` form was given.
  final bool yellowbackForm;

  /// Why it is invalid, empty when valid.
  final String message;

  const AddressCheck({
    required this.valid,
    required this.kind,
    required this.yellowbackForm,
    required this.message,
  });

  @override
  int get hashCode =>
      valid.hashCode ^
      kind.hashCode ^
      yellowbackForm.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressCheck &&
          runtimeType == other.runtimeType &&
          valid == other.valid &&
          kind == other.kind &&
          yellowbackForm == other.yellowbackForm &&
          message == other.message;
}

/// A receive address: `address` is the one of `kind`; for the transparent kinds `ye` and `s`
/// are the two forms of the same key, for a shielded address both are empty.
class AddressPair {
  /// The Yellowback form (`ye…` / `yt…` / `yr…`).
  final String ye;

  /// The transparent form (`s1…` / `sm…`).
  final String s;

  /// The derivation path, or `imported`.
  final String path;

  /// `false` for an imported key (not covered by the seed backup).
  final bool coveredBySeed;

  /// The address of `kind` (`s…`, `ye…` or `ys1…`).
  final String address;

  /// The kind of `address`.
  final ReceiveKind kind;

  const AddressPair({
    required this.ye,
    required this.s,
    required this.path,
    required this.coveredBySeed,
    required this.address,
    required this.kind,
  });

  @override
  int get hashCode =>
      ye.hashCode ^
      s.hashCode ^
      path.hashCode ^
      coveredBySeed.hashCode ^
      address.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressPair &&
          runtimeType == other.runtimeType &&
          ye == other.ye &&
          s == other.s &&
          path == other.path &&
          coveredBySeed == other.coveredBySeed &&
          address == other.address &&
          kind == other.kind;
}

/// [`balances`] (plan §3.4 shape; computed from classes, §3.7).
class Balances {
  /// YEC available (class `YEC`), zat.
  final PlatformInt64 yecZat;

  /// YEC reserved for YED fees (class `FEE_RESERVE`), zat.
  final PlatformInt64 yecReservedZat;

  /// YEC change of own unconfirmed transactions, zat (in neither balance).
  final PlatformInt64 yecPendingZat;

  /// YED (class `TOKEN`), cents.
  final PlatformInt64 yedCents;

  /// Pending YED (class `PENDING_TOKEN`), cents.
  final PlatformInt64 yedPendingCents;

  /// `GetPrice.pMint` at the last sync, micro-USD per YEC; `None` when undefined.
  final PlatformInt64? priceMicroUsd;

  /// Outputs of `TOKEN_VALUE` the server does not list (class `HELD`): count.
  final PlatformInt64 heldCount;

  /// The height the wallet last synced to (0 = never).
  final PlatformInt64 syncHeight;

  /// The YEC a YED send needs at least (`fee + 2 · TOKEN_VALUE`), zat.
  final PlatformInt64 yedSendMinZat;

  /// Private (shielded, Sapling) YEC: every unspent note, zat. Never used for YED or fees.
  final PlatformInt64 yecShieldedZat;

  /// Private YEC spendable now, zat (0 until the scan reaches the tip).
  final PlatformInt64 yecShieldedSpendableZat;

  /// Private YEC waiting for a confirmation or for the scan, zat (own change + incoming).
  final PlatformInt64 yecShieldedPendingZat;

  /// The height the private wallet is scanned to without gaps (0 = never).
  final PlatformInt64 shieldedScannedHeight;

  /// Scanned to the tip: private sending is available ("sending available at 100%").
  final bool shieldedSendable;

  const Balances({
    required this.yecZat,
    required this.yecReservedZat,
    required this.yecPendingZat,
    required this.yedCents,
    required this.yedPendingCents,
    this.priceMicroUsd,
    required this.heldCount,
    required this.syncHeight,
    required this.yedSendMinZat,
    required this.yecShieldedZat,
    required this.yecShieldedSpendableZat,
    required this.yecShieldedPendingZat,
    required this.shieldedScannedHeight,
    required this.shieldedSendable,
  });

  static Future<Balances> default_() =>
      RustLib.instance.api.crateApiBalancesDefault();

  @override
  int get hashCode =>
      yecZat.hashCode ^
      yecReservedZat.hashCode ^
      yecPendingZat.hashCode ^
      yedCents.hashCode ^
      yedPendingCents.hashCode ^
      priceMicroUsd.hashCode ^
      heldCount.hashCode ^
      syncHeight.hashCode ^
      yedSendMinZat.hashCode ^
      yecShieldedZat.hashCode ^
      yecShieldedSpendableZat.hashCode ^
      yecShieldedPendingZat.hashCode ^
      shieldedScannedHeight.hashCode ^
      shieldedSendable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Balances &&
          runtimeType == other.runtimeType &&
          yecZat == other.yecZat &&
          yecReservedZat == other.yecReservedZat &&
          yecPendingZat == other.yecPendingZat &&
          yedCents == other.yedCents &&
          yedPendingCents == other.yedPendingCents &&
          priceMicroUsd == other.priceMicroUsd &&
          heldCount == other.heldCount &&
          syncHeight == other.syncHeight &&
          yedSendMinZat == other.yedSendMinZat &&
          yecShieldedZat == other.yecShieldedZat &&
          yecShieldedSpendableZat == other.yecShieldedSpendableZat &&
          yecShieldedPendingZat == other.yecShieldedPendingZat &&
          shieldedScannedHeight == other.shieldedScannedHeight &&
          shieldedSendable == other.shieldedSendable;
}

/// One `ListClaimable` row (the liquidator persona, plan §5.3).
class ClaimableItem {
  /// The vault's mint txid.
  final String vaultTxid;

  /// The owner, `ye…`.
  final String ownerAddress;

  /// The debt to burn, cents (the wallet must hold at least this).
  final PlatformInt64 cents;

  /// The collateral, zat.
  final PlatformInt64 collateralZat;

  /// `claimHeight`.
  final PlatformInt64 claimHeight;

  /// `a` (underwater at `pClaim`) or `b` (notice + emergency price).
  final String claimPath;

  /// `pClaim` at the node's tip, micro-USD per YEC.
  final PlatformInt64 pClaimMicroUsd;

  /// The enforcement fee, zat.
  final PlatformInt64 feeZat;

  /// The attestor fee, zat.
  final PlatformInt64 attestFeeZat;

  /// RED-5's residual to the owner, zat.
  final PlatformInt64 residualZat;

  /// What the claimant keeps, zat.
  final PlatformInt64 claimantZat;

  /// The enforcement fee payee (`s…`), empty under FEE-0.
  final String payee;

  const ClaimableItem({
    required this.vaultTxid,
    required this.ownerAddress,
    required this.cents,
    required this.collateralZat,
    required this.claimHeight,
    required this.claimPath,
    required this.pClaimMicroUsd,
    required this.feeZat,
    required this.attestFeeZat,
    required this.residualZat,
    required this.claimantZat,
    required this.payee,
  });

  @override
  int get hashCode =>
      vaultTxid.hashCode ^
      ownerAddress.hashCode ^
      cents.hashCode ^
      collateralZat.hashCode ^
      claimHeight.hashCode ^
      claimPath.hashCode ^
      pClaimMicroUsd.hashCode ^
      feeZat.hashCode ^
      attestFeeZat.hashCode ^
      residualZat.hashCode ^
      claimantZat.hashCode ^
      payee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClaimableItem &&
          runtimeType == other.runtimeType &&
          vaultTxid == other.vaultTxid &&
          ownerAddress == other.ownerAddress &&
          cents == other.cents &&
          collateralZat == other.collateralZat &&
          claimHeight == other.claimHeight &&
          claimPath == other.claimPath &&
          pClaimMicroUsd == other.pClaimMicroUsd &&
          feeZat == other.feeZat &&
          attestFeeZat == other.attestFeeZat &&
          residualZat == other.residualZat &&
          claimantZat == other.claimantZat &&
          payee == other.payee;
}

/// The result of [`create_wallet`].
class Created {
  /// The wallet id (the primary address's key hash, hex-prefixed).
  final String walletId;

  /// The mnemonic, **only when this call generated it** (the app stores it in the platform
  /// keystore and shows it once for backup); `None` when the caller supplied the words.
  final String? seedWords;

  /// The primary receive address, `ye…` form.
  final String addressYe;

  const Created({
    required this.walletId,
    this.seedWords,
    required this.addressYe,
  });

  @override
  int get hashCode =>
      walletId.hashCode ^ seedWords.hashCode ^ addressYe.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Created &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          seedWords == other.seedWords &&
          addressYe == other.addressYe;
}

/// A default endpoint for a network (`docs/release.md` "Default endpoints"; the mainnet and
/// testnet lists are empty until the owner supplies them, plan §8 Q4).
class DefaultEndpoint {
  /// `host:port`.
  final String address;

  /// Plain HTTP/2 (regtest only).
  final bool plain;

  const DefaultEndpoint({required this.address, required this.plain});

  @override
  int get hashCode => address.hashCode ^ plain.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DefaultEndpoint &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          plain == other.plain;
}

/// The node's dry run of a preview (`ValidateRawTransaction`).
class DryRun {
  /// `valid`.
  final bool valid;

  /// `verdict`.
  final String verdict;

  /// `burned`, cents.
  final PlatformInt64 burnedCents;

  /// `wouldBeRejected`.
  final bool wouldBeRejected;

  /// `yedIn`, cents.
  final PlatformInt64 yedInCents;

  /// `yedOut`, cents.
  final PlatformInt64 yedOutCents;

  /// `true` when the gate would accept this validation.
  final bool accepted;

  const DryRun({
    required this.valid,
    required this.verdict,
    required this.burnedCents,
    required this.wouldBeRejected,
    required this.yedInCents,
    required this.yedOutCents,
    required this.accepted,
  });

  @override
  int get hashCode =>
      valid.hashCode ^
      verdict.hashCode ^
      burnedCents.hashCode ^
      wouldBeRejected.hashCode ^
      yedInCents.hashCode ^
      yedOutCents.hashCode ^
      accepted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DryRun &&
          runtimeType == other.runtimeType &&
          valid == other.valid &&
          verdict == other.verdict &&
          burnedCents == other.burnedCents &&
          wouldBeRejected == other.wouldBeRejected &&
          yedInCents == other.yedInCents &&
          yedOutCents == other.yedOutCents &&
          accepted == other.accepted;
}

/// What kind of failure a [`YewError`] is; `message` is always the text to show.
enum ErrorKind {
  /// No wallet is open ([`unlock`] first).
  locked,

  /// A wallet is already open ([`lock`] first).
  alreadyOpen,

  /// A call the core does not offer yet (none in W4; kept for the app's exhaustive match).
  notYetImplemented,

  /// The broadcast gate refused (the node's verdict is in `message`, D-W-5).
  gate,

  /// The server could not be reached or answered with an error.
  network,

  /// The server offers no usable Yellowback service (contract rule 1).
  yellowbackUnavailable,

  /// The builder refused (`change-floor`, `insufficient-yed`, bad address, ...).
  refused,

  /// Not enough YEC for the fee of a YED operation (§3.7 item 4).
  needYecForFees,

  /// Bad input from the app (mnemonic, address, WIF, amount).
  input,

  /// A preview id that no longer exists.
  previewExpired,

  /// Private (shielded) sending needs the wallet scanned to the tip ("syncing… sending
  /// available at 100%"): sync, then try again.
  shieldedNotReady,

  /// The Sapling proving parameters are not downloaded yet: call [`download_params`] (the
  /// one-time "Preparing private sending (52 MB)" sheet), then confirm again.
  paramsMissing,

  /// Anything else (storage, key derivation).
  other,
}

/// One history row.
class HistoryItem {
  /// Txid, display form.
  final String txid;

  /// Block height (0 while pending).
  final PlatformInt64 height;

  /// Unconfirmed.
  final bool pending;

  /// Net YEC, zat (negative = sent).
  final PlatformInt64 yecDeltaZat;

  /// Net YED, cents (negative = sent).
  final PlatformInt64 yedDeltaCents;

  /// The verdict-derived label (`received $12.34`, `sent $12.34`, `minted $…`, ...), or the
  /// CLI's fallbacks for an unlabelled payload.
  final String label;

  /// The node's verdict, when known.
  final String verdict;

  /// The Yellowback kind (`transfer`, `mint`, ...), when known.
  final String kind;

  /// The transaction carries an `OP_RETURN`.
  final bool hasPayload;

  /// The transaction has shielded components (a transparent leg of a shielded tx, or a
  /// private send / receipt).
  final bool shielded;

  /// The memo of a private receipt or send (text), empty when none.
  final String memo;

  const HistoryItem({
    required this.txid,
    required this.height,
    required this.pending,
    required this.yecDeltaZat,
    required this.yedDeltaCents,
    required this.label,
    required this.verdict,
    required this.kind,
    required this.hasPayload,
    required this.shielded,
    required this.memo,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      height.hashCode ^
      pending.hashCode ^
      yecDeltaZat.hashCode ^
      yedDeltaCents.hashCode ^
      label.hashCode ^
      verdict.hashCode ^
      kind.hashCode ^
      hasPayload.hashCode ^
      shielded.hashCode ^
      memo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryItem &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          height == other.height &&
          pending == other.pending &&
          yecDeltaZat == other.yecDeltaZat &&
          yedDeltaCents == other.yedDeltaCents &&
          label == other.label &&
          verdict == other.verdict &&
          kind == other.kind &&
          hasPayload == other.hasPayload &&
          shielded == other.shielded &&
          memo == other.memo;
}

/// One page of [`history`].
class HistoryPage {
  /// The rows of this page, pending first then newest first.
  final List<HistoryItem> rows;

  /// The page index requested.
  final int page;

  /// Total rows.
  final PlatformInt64 total;

  const HistoryPage({
    required this.rows,
    required this.page,
    required this.total,
  });

  @override
  int get hashCode => rows.hashCode ^ page.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryPage &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          page == other.page &&
          total == other.total;
}

/// [`mint_estimate`]: what the Mint screen shows before anything is signed (plan §5.3).
class MintEstimate {
  /// Cents to mint.
  final PlatformInt64 cents;

  /// The lock in blocks.
  final int lockBlocks;

  /// The term class letter (`A`, `B`, `C`).
  final String termClass;

  /// `R`, the reference height the two transactions cite.
  final PlatformInt64 refHeight;

  /// `R + lockBlocks`: when the owner may redeem.
  final PlatformInt64 lockHeight;

  /// `lockHeight + GRACE`: when a liquidator may claim.
  final PlatformInt64 claimHeight;

  /// `R + REF_WINDOW`: the carrier and the MINT expire here.
  final PlatformInt64 expiryHeight;

  /// `requiredZat` as the node reports it.
  final PlatformInt64 requiredZat;

  /// The collateral the MINT will lock (rounded as `BuildMint` does).
  final PlatformInt64 collateralZat;

  /// The enforcement fee, zat (0 under FEE-0).
  final PlatformInt64 feeZat;

  /// The attestor fee, zat (0 under AFEE-0).
  final PlatformInt64 attestFeeZat;

  /// The enforcement fee payee (`s…`), empty under FEE-0. The amount is checked against
  /// FEE-1 locally; the payee's eligibility is the node's to judge (audit G-2).
  final String payee;

  /// `CARRIER_VALUE`, zat.
  final PlatformInt64 carrierZat;

  /// `TOKEN_VALUE` for the new YED output, zat.
  final PlatformInt64 tokenZat;

  /// The two network fees, zat.
  final PlatformInt64 networkFeeZat;

  /// Everything the two steps need from YEC, zat.
  final PlatformInt64 totalZat;

  /// Spendable `YEC` + `FEE_RESERVE`, zat.
  final PlatformInt64 availableZat;

  /// `available_zat >= total_zat`.
  final bool affordable;

  /// `pMint` at `R`, micro-USD per YEC; `None` when undefined.
  final PlatformInt64? pMintMicroUsd;

  /// `armed` at `R`.
  final bool armed;

  /// The attestor `seq`s the bundle would carry.
  final Uint32List bundleSeqs;

  const MintEstimate({
    required this.cents,
    required this.lockBlocks,
    required this.termClass,
    required this.refHeight,
    required this.lockHeight,
    required this.claimHeight,
    required this.expiryHeight,
    required this.requiredZat,
    required this.collateralZat,
    required this.feeZat,
    required this.attestFeeZat,
    required this.payee,
    required this.carrierZat,
    required this.tokenZat,
    required this.networkFeeZat,
    required this.totalZat,
    required this.availableZat,
    required this.affordable,
    this.pMintMicroUsd,
    required this.armed,
    required this.bundleSeqs,
  });

  @override
  int get hashCode =>
      cents.hashCode ^
      lockBlocks.hashCode ^
      termClass.hashCode ^
      refHeight.hashCode ^
      lockHeight.hashCode ^
      claimHeight.hashCode ^
      expiryHeight.hashCode ^
      requiredZat.hashCode ^
      collateralZat.hashCode ^
      feeZat.hashCode ^
      attestFeeZat.hashCode ^
      payee.hashCode ^
      carrierZat.hashCode ^
      tokenZat.hashCode ^
      networkFeeZat.hashCode ^
      totalZat.hashCode ^
      availableZat.hashCode ^
      affordable.hashCode ^
      pMintMicroUsd.hashCode ^
      armed.hashCode ^
      bundleSeqs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintEstimate &&
          runtimeType == other.runtimeType &&
          cents == other.cents &&
          lockBlocks == other.lockBlocks &&
          termClass == other.termClass &&
          refHeight == other.refHeight &&
          lockHeight == other.lockHeight &&
          claimHeight == other.claimHeight &&
          expiryHeight == other.expiryHeight &&
          requiredZat == other.requiredZat &&
          collateralZat == other.collateralZat &&
          feeZat == other.feeZat &&
          attestFeeZat == other.attestFeeZat &&
          payee == other.payee &&
          carrierZat == other.carrierZat &&
          tokenZat == other.tokenZat &&
          networkFeeZat == other.networkFeeZat &&
          totalZat == other.totalZat &&
          availableZat == other.availableZat &&
          affordable == other.affordable &&
          pMintMicroUsd == other.pMintMicroUsd &&
          armed == other.armed &&
          bundleSeqs == other.bundleSeqs;
}

/// One `mints` row (plan §5.3, README "the two-step state machine is a table"): a mint or a
/// claim from the moment its carrier is broadcast. `state` is the stored name
/// (`CARRIER_SENT`, `CARRIER_CONFIRMED`, `MAIN_SENT`, `DONE`, `LAPSED`, `SWEEP_SENT`, `SWEPT`,
/// `FAILED`). Heights are judged against `tip`, the last height the wallet synced to.
class MintStatus {
  /// The row id.
  final PlatformInt64 mintId;

  /// `mint` or `claim`.
  final String kind;

  /// The stored state name.
  final String state;

  /// The tip when the carrier was broadcast.
  final PlatformInt64 createdHeight;

  /// Cents minted (mint) or the debt burned (claim).
  final PlatformInt64 cents;

  /// `lockBlocks` (mint).
  final int lockBlocks;

  /// The term class letter.
  final String termClass;

  /// `R`.
  final PlatformInt64 refHeight;

  /// The vault's `lockHeight`.
  final PlatformInt64 lockHeight;

  /// The vault's `claimHeight`.
  final PlatformInt64 claimHeight;

  /// `R + REF_WINDOW`.
  final PlatformInt64 expiryHeight;

  /// The collateral, zat.
  final PlatformInt64 collateralZat;

  /// The enforcement fee, zat.
  final PlatformInt64 feeZat;

  /// The attestor fee, zat.
  final PlatformInt64 attestFeeZat;

  /// A claim's residual to the vault owner, zat.
  final PlatformInt64 residualZat;

  /// The enforcement fee payee (`s…`), empty under FEE-0.
  final String payee;

  /// The attestor fee payee (`s…`), empty under AFEE-0.
  final String attestPayee;

  /// The bundle's `seq`s as `"0,1,2"`.
  final String bundleSeqs;

  /// The carrier funding txid (display form).
  final String carrierTxid;

  /// The MINT / CLAIM txid, empty until `MAIN_SENT`.
  final String mainTxid;

  /// The sweep txid, empty until `SWEEP_SENT`.
  final String sweepTxid;

  /// A claim's vault txid, empty for a mint.
  final String vaultTxid;

  /// The last synced height the flags below were judged at.
  final PlatformInt64 tip;

  /// `CARRIER_SENT`, `CARRIER_CONFIRMED` or `MAIN_SENT`: still moving.
  final bool inProgress;

  /// The node would still accept the main transaction (`CheckExpiry` at `tip`).
  final bool windowOpen;

  /// Blocks until the window closes (0 when closed).
  final PlatformInt64 blocksLeft;

  /// `CARRIER_CONFIRMED` with the window open: [`mint_finish`] may be called.
  final bool canFinish;

  /// `LAPSED`: [`mint_sweep`] may be called.
  final bool canSweep;

  /// Why the row failed or lapsed, for the screen.
  final String note;

  const MintStatus({
    required this.mintId,
    required this.kind,
    required this.state,
    required this.createdHeight,
    required this.cents,
    required this.lockBlocks,
    required this.termClass,
    required this.refHeight,
    required this.lockHeight,
    required this.claimHeight,
    required this.expiryHeight,
    required this.collateralZat,
    required this.feeZat,
    required this.attestFeeZat,
    required this.residualZat,
    required this.payee,
    required this.attestPayee,
    required this.bundleSeqs,
    required this.carrierTxid,
    required this.mainTxid,
    required this.sweepTxid,
    required this.vaultTxid,
    required this.tip,
    required this.inProgress,
    required this.windowOpen,
    required this.blocksLeft,
    required this.canFinish,
    required this.canSweep,
    required this.note,
  });

  @override
  int get hashCode =>
      mintId.hashCode ^
      kind.hashCode ^
      state.hashCode ^
      createdHeight.hashCode ^
      cents.hashCode ^
      lockBlocks.hashCode ^
      termClass.hashCode ^
      refHeight.hashCode ^
      lockHeight.hashCode ^
      claimHeight.hashCode ^
      expiryHeight.hashCode ^
      collateralZat.hashCode ^
      feeZat.hashCode ^
      attestFeeZat.hashCode ^
      residualZat.hashCode ^
      payee.hashCode ^
      attestPayee.hashCode ^
      bundleSeqs.hashCode ^
      carrierTxid.hashCode ^
      mainTxid.hashCode ^
      sweepTxid.hashCode ^
      vaultTxid.hashCode ^
      tip.hashCode ^
      inProgress.hashCode ^
      windowOpen.hashCode ^
      blocksLeft.hashCode ^
      canFinish.hashCode ^
      canSweep.hashCode ^
      note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintStatus &&
          runtimeType == other.runtimeType &&
          mintId == other.mintId &&
          kind == other.kind &&
          state == other.state &&
          createdHeight == other.createdHeight &&
          cents == other.cents &&
          lockBlocks == other.lockBlocks &&
          termClass == other.termClass &&
          refHeight == other.refHeight &&
          lockHeight == other.lockHeight &&
          claimHeight == other.claimHeight &&
          expiryHeight == other.expiryHeight &&
          collateralZat == other.collateralZat &&
          feeZat == other.feeZat &&
          attestFeeZat == other.attestFeeZat &&
          residualZat == other.residualZat &&
          payee == other.payee &&
          attestPayee == other.attestPayee &&
          bundleSeqs == other.bundleSeqs &&
          carrierTxid == other.carrierTxid &&
          mainTxid == other.mainTxid &&
          sweepTxid == other.sweepTxid &&
          vaultTxid == other.vaultTxid &&
          tip == other.tip &&
          inProgress == other.inProgress &&
          windowOpen == other.windowOpen &&
          blocksLeft == other.blocksLeft &&
          canFinish == other.canFinish &&
          canSweep == other.canSweep &&
          note == other.note;
}

/// The terms of a [`MintEstimate`] the user confirmed, passed back to [`mint_start`] so the
/// server's second answer may not differ from what was shown (audit G-2).
class MintTerms {
  /// `MintEstimate::collateral_zat`.
  final PlatformInt64 collateralZat;

  /// `MintEstimate::fee_zat`.
  final PlatformInt64 feeZat;

  /// `MintEstimate::payee`.
  final String payee;

  /// `MintEstimate::term_class`.
  final String termClass;

  const MintTerms({
    required this.collateralZat,
    required this.feeZat,
    required this.payee,
    required this.termClass,
  });

  @override
  int get hashCode =>
      collateralZat.hashCode ^
      feeZat.hashCode ^
      payee.hashCode ^
      termClass.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintTerms &&
          runtimeType == other.runtimeType &&
          collateralZat == other.collateralZat &&
          feeZat == other.feeZat &&
          payee == other.payee &&
          termClass == other.termClass;
}

/// The direction of [`move_preview`].
enum MoveDirection {
  /// Public YEC into the private balance (shield, to the wallet's own `ys1…`).
  toPrivate,

  /// Private YEC to the wallet's own public `s…` address (unshield; the amount becomes
  /// visible on the chain, `reveals_shielded`).
  toPublic,
}

/// The network a wallet is for.
enum NetworkId {
  /// Regtest (the devnet).
  regtest,

  /// Testnet.
  testnet,

  /// Mainnet.
  mainnet,
}

/// One event of [`download_params`].
class ParamsProgress {
  /// The file being fetched (`sapling-spend.params` / `sapling-output.params`).
  final String file;

  /// Bytes received so far in this call.
  final PlatformInt64 doneBytes;

  /// Bytes this call fetches.
  final PlatformInt64 totalBytes;

  /// The last event: both files verified and in place.
  final bool finished;

  const ParamsProgress({
    required this.file,
    required this.doneBytes,
    required this.totalBytes,
    required this.finished,
  });

  @override
  int get hashCode =>
      file.hashCode ^
      doneBytes.hashCode ^
      totalBytes.hashCode ^
      finished.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParamsProgress &&
          runtimeType == other.runtimeType &&
          file == other.file &&
          doneBytes == other.doneBytes &&
          totalBytes == other.totalBytes &&
          finished == other.finished;
}

/// [`params_status`]: the Sapling proving parameters on this device.
class ParamsStatus {
  /// Both files are present (pinned lengths): a private send can be proved.
  final bool ready;

  /// Both were hashed against their SHA-256 pins in this session.
  final bool verified;

  /// Bytes still to download.
  final PlatformInt64 missingBytes;

  /// Bytes of a full download (51,551,256).
  final PlatformInt64 totalBytes;

  const ParamsStatus({
    required this.ready,
    required this.verified,
    required this.missingBytes,
    required this.totalBytes,
  });

  @override
  int get hashCode =>
      ready.hashCode ^
      verified.hashCode ^
      missingBytes.hashCode ^
      totalBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParamsStatus &&
          runtimeType == other.runtimeType &&
          ready == other.ready &&
          verified == other.verified &&
          missingBytes == other.missingBytes &&
          totalBytes == other.totalBytes;
}

/// Which receive address [`receive_address`] returns.
enum ReceiveKind {
  /// The transparent `s…` form (YEC from any wallet).
  transparent,

  /// The private Sapling `ys1…` address (shielded YEC, memos).
  shielded,

  /// The Yellowback `ye…` form of the transparent address (YED, mint).
  yed,
}

/// One recipient of a YED send.
class Recipient {
  /// `ye…` / `yr…` / `s…`.
  final String address;

  /// Cents.
  final PlatformInt64 cents;

  const Recipient({required this.address, required this.cents});

  @override
  int get hashCode => address.hashCode ^ cents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Recipient &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          cents == other.cents;
}

/// [`redeem_preview`]: the signed REDEEM (or VOID release) waiting for [`redeem_confirm`]
/// (audit G-2): everything the Vault screen shows before the slider.
class RedeemPreview {
  /// Pass to [`redeem_confirm`].
  final String previewId;

  /// The vault's mint txid.
  final String vaultTxid;

  /// `redeem` (ACTIVE) or `release` (VOID).
  final String kind;

  /// Cents burned (the debt plus any sub-dollar remainder).
  final PlatformInt64 burnCents;

  /// The sub-dollar remainder burned on top of the debt.
  final PlatformInt64 extraBurnCents;

  /// YED change, cents.
  final PlatformInt64 changeCents;

  /// YED inputs spent.
  final int yedInputs;

  /// The enforcement fee, zat (FEE-1, checked locally).
  final PlatformInt64 feeZat;

  /// The enforcement fee payee (`s…`), empty under FEE-0.
  final String payee;

  /// The collateral returned, zat.
  final PlatformInt64 collateralZat;

  /// The own address it returns to.
  final String collateralAddress;

  /// `nLockTime` (= `lockHeight`).
  final PlatformInt64 lockTime;

  /// `nExpiryHeight`.
  final PlatformInt64 expiryHeight;

  /// The txid the broadcast will have.
  final String txid;

  const RedeemPreview({
    required this.previewId,
    required this.vaultTxid,
    required this.kind,
    required this.burnCents,
    required this.extraBurnCents,
    required this.changeCents,
    required this.yedInputs,
    required this.feeZat,
    required this.payee,
    required this.collateralZat,
    required this.collateralAddress,
    required this.lockTime,
    required this.expiryHeight,
    required this.txid,
  });

  @override
  int get hashCode =>
      previewId.hashCode ^
      vaultTxid.hashCode ^
      kind.hashCode ^
      burnCents.hashCode ^
      extraBurnCents.hashCode ^
      changeCents.hashCode ^
      yedInputs.hashCode ^
      feeZat.hashCode ^
      payee.hashCode ^
      collateralZat.hashCode ^
      collateralAddress.hashCode ^
      lockTime.hashCode ^
      expiryHeight.hashCode ^
      txid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RedeemPreview &&
          runtimeType == other.runtimeType &&
          previewId == other.previewId &&
          vaultTxid == other.vaultTxid &&
          kind == other.kind &&
          burnCents == other.burnCents &&
          extraBurnCents == other.extraBurnCents &&
          changeCents == other.changeCents &&
          yedInputs == other.yedInputs &&
          feeZat == other.feeZat &&
          payee == other.payee &&
          collateralZat == other.collateralZat &&
          collateralAddress == other.collateralAddress &&
          lockTime == other.lockTime &&
          expiryHeight == other.expiryHeight &&
          txid == other.txid;
}

/// The result of [`redeem`]: the REDEEM (or the release of a VOID vault) was broadcast.
class RedeemResult {
  /// The txid, display form.
  final String txid;

  /// The node's verdict on the broadcast bytes.
  final String verdict;

  /// `redeem` (ACTIVE) or `release` (VOID).
  final String kind;

  /// Cents burned (the debt plus any sub-dollar remainder).
  final PlatformInt64 burnCents;

  /// The sub-dollar remainder burned on top of the debt.
  final PlatformInt64 extraBurnCents;

  /// YED change, cents.
  final PlatformInt64 changeCents;

  /// The enforcement fee, zat.
  final PlatformInt64 feeZat;

  /// The enforcement fee payee (`s…`), empty under FEE-0.
  final String payee;

  /// The collateral returned, zat.
  final PlatformInt64 collateralZat;

  /// The own address it returns to.
  final String collateralAddress;

  /// `nLockTime` (= `lockHeight`).
  final PlatformInt64 lockTime;

  /// `nExpiryHeight`.
  final PlatformInt64 expiryHeight;

  const RedeemResult({
    required this.txid,
    required this.verdict,
    required this.kind,
    required this.burnCents,
    required this.extraBurnCents,
    required this.changeCents,
    required this.feeZat,
    required this.payee,
    required this.collateralZat,
    required this.collateralAddress,
    required this.lockTime,
    required this.expiryHeight,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      verdict.hashCode ^
      kind.hashCode ^
      burnCents.hashCode ^
      extraBurnCents.hashCode ^
      changeCents.hashCode ^
      feeZat.hashCode ^
      payee.hashCode ^
      collateralZat.hashCode ^
      collateralAddress.hashCode ^
      lockTime.hashCode ^
      expiryHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RedeemResult &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          verdict == other.verdict &&
          kind == other.kind &&
          burnCents == other.burnCents &&
          extraBurnCents == other.extraBurnCents &&
          changeCents == other.changeCents &&
          feeZat == other.feeZat &&
          payee == other.payee &&
          collateralZat == other.collateralZat &&
          collateralAddress == other.collateralAddress &&
          lockTime == other.lockTime &&
          expiryHeight == other.expiryHeight;
}

/// The result of a confirm.
class SendResult {
  /// The txid, display form.
  final String txid;

  /// The node's verdict on the broadcast bytes (`ok`), empty on the YEC path against a
  /// server without Yellowback.
  final String verdict;

  const SendResult({required this.txid, required this.verdict});

  @override
  int get hashCode => txid.hashCode ^ verdict.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendResult &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          verdict == other.verdict;
}

/// [`probe_server`]: what a server answers before any wallet is open.
class ServerProbe {
  /// The server's `version`.
  final String serverVersion;

  /// The server's chain name.
  final String chainName;

  /// The tip (the default birthday of a new wallet).
  final PlatformInt64 tip;

  /// `taddrSupport`.
  final bool taddrSupport;

  /// Yellowback on this server.
  final YellowbackStatus yellowback;

  const ServerProbe({
    required this.serverVersion,
    required this.chainName,
    required this.tip,
    required this.taddrSupport,
    required this.yellowback,
  });

  @override
  int get hashCode =>
      serverVersion.hashCode ^
      chainName.hashCode ^
      tip.hashCode ^
      taddrSupport.hashCode ^
      yellowback.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerProbe &&
          runtimeType == other.runtimeType &&
          serverVersion == other.serverVersion &&
          chainName == other.chainName &&
          tip == other.tip &&
          taddrSupport == other.taddrSupport &&
          yellowback == other.yellowback;
}

/// [`status`]: the open wallet and its server.
class Status {
  /// The wallet id.
  final String walletId;

  /// The network.
  final NetworkId network;

  /// `host:port`.
  final String server;

  /// Plain HTTP/2 (regtest only).
  final bool plain;

  /// A certificate is pinned for this server (the only trust anchor).
  final bool caPinned;

  /// The server's `version`.
  final String serverVersion;

  /// The server's chain name.
  final String chainName;

  /// `consensusBranchId`, hex.
  final String branchId;

  /// The tip.
  final PlatformInt64 tip;

  /// The wallet's birthday height.
  final PlatformInt64 birthday;

  /// The height the wallet last synced to (0 = never).
  final PlatformInt64 syncHeight;

  /// The number of addresses the wallet watches.
  final PlatformInt64 addresses;

  /// Yellowback on this server.
  final YellowbackStatus yellowback;

  /// The core's version.
  final String coreVersion;

  const Status({
    required this.walletId,
    required this.network,
    required this.server,
    required this.plain,
    required this.caPinned,
    required this.serverVersion,
    required this.chainName,
    required this.branchId,
    required this.tip,
    required this.birthday,
    required this.syncHeight,
    required this.addresses,
    required this.yellowback,
    required this.coreVersion,
  });

  @override
  int get hashCode =>
      walletId.hashCode ^
      network.hashCode ^
      server.hashCode ^
      plain.hashCode ^
      caPinned.hashCode ^
      serverVersion.hashCode ^
      chainName.hashCode ^
      branchId.hashCode ^
      tip.hashCode ^
      birthday.hashCode ^
      syncHeight.hashCode ^
      addresses.hashCode ^
      yellowback.hashCode ^
      coreVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Status &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          network == other.network &&
          server == other.server &&
          plain == other.plain &&
          caPinned == other.caPinned &&
          serverVersion == other.serverVersion &&
          chainName == other.chainName &&
          branchId == other.branchId &&
          tip == other.tip &&
          birthday == other.birthday &&
          syncHeight == other.syncHeight &&
          addresses == other.addresses &&
          yellowback == other.yellowback &&
          coreVersion == other.coreVersion;
}

/// One event of [`sync_now`].
class SyncEvent {
  /// The stage.
  final SyncStage stage;

  /// A one-line description (or the error on `Failed`).
  final String message;

  /// The tip (from `Probing` on).
  final PlatformInt64 tip;

  /// The height synced to (`Done`).
  final PlatformInt64 syncHeight;

  /// Yellowback usable on this server (from `Probing` on).
  final bool yellowbackUsable;

  /// Overall progress 0..=100 (transparent scan to 10, private scan 10..95, memos, done).
  final int percent;

  /// The height the private wallet is scanned to.
  final PlatformInt64 shieldedHeight;

  /// Private sending is available (scanned to the tip).
  final bool shieldedSendable;

  /// On `Done`: why the private sync did not run or failed, empty when it succeeded (the
  /// transparent sync still counts; YED and transparent YEC are unaffected).
  final String shieldedMessage;

  const SyncEvent({
    required this.stage,
    required this.message,
    required this.tip,
    required this.syncHeight,
    required this.yellowbackUsable,
    required this.percent,
    required this.shieldedHeight,
    required this.shieldedSendable,
    required this.shieldedMessage,
  });

  @override
  int get hashCode =>
      stage.hashCode ^
      message.hashCode ^
      tip.hashCode ^
      syncHeight.hashCode ^
      yellowbackUsable.hashCode ^
      percent.hashCode ^
      shieldedHeight.hashCode ^
      shieldedSendable.hashCode ^
      shieldedMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncEvent &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          message == other.message &&
          tip == other.tip &&
          syncHeight == other.syncHeight &&
          yellowbackUsable == other.yellowbackUsable &&
          percent == other.percent &&
          shieldedHeight == other.shieldedHeight &&
          shieldedSendable == other.shieldedSendable &&
          shieldedMessage == other.shieldedMessage;
}

/// A stage of [`sync_now`].
enum SyncStage {
  /// Opening the channel.
  connecting,

  /// `GetLightdInfo` + `GetYellowbackInfo`.
  probing,

  /// The §3.2 loop.
  scanning,

  /// The private (Sapling) scan: `percent`, `shielded_height` move.
  shieldedScanning,

  /// Fetching the memos and status of private transactions.
  shieldedMemos,

  /// Finished; `tip` and `sync_height` are set.
  done,

  /// Failed; `message` is set.
  failed,
}

/// One own vault as `GetVault` last reported it (the Yellowback screen, plan §5.3).
class VaultSummary {
  /// The mint txid (the vault outpoint is `txid:0`).
  final String vaultTxid;

  /// `ACTIVE`, `VOID`, `CLOSED`, `CLAIMED`.
  final String status;

  /// The owner address, `ye…` form (an own key).
  final String ownerAddress;

  /// The term class letter.
  final String termClass;

  /// Cents minted (the debt).
  final PlatformInt64 cents;

  /// Collateral, zat.
  final PlatformInt64 collateralZat;

  /// `lockHeight`.
  final PlatformInt64 lockHeight;

  /// `claimHeight`.
  final PlatformInt64 claimHeight;

  /// `mintHeight`.
  final PlatformInt64 mintHeight;

  /// The last synced height the flags below were judged at.
  final PlatformInt64 tip;

  /// `ACTIVE` or `VOID`: still spendable by its owner.
  final bool open;

  /// `ACTIVE` and `tip >= lockHeight`: [`redeem`] builds the owner-path REDEEM.
  final bool redeemable;

  /// Blocks until `lockHeight` (0 once reached).
  final PlatformInt64 blocksUntilRedeem;

  /// `VOID`: [`redeem`] releases the collateral without a payload.
  final bool releasable;

  /// `claimable` as the node judged it at its tip (a liquidator may take it).
  final bool claimable;

  /// `underwaterAt`, micro-USD per YEC (0 when undefined).
  final PlatformInt64 underwaterAtMicroUsd;

  /// The last sync's `pMint` is at or below `underwaterAt`: the warning.
  final bool underwater;

  /// `closeHeight`, 0 while open.
  final PlatformInt64 closeHeight;

  /// `closingTxid`, empty while open.
  final String closingTxid;

  /// `voidReason`, empty unless VOID.
  final String voidReason;

  const VaultSummary({
    required this.vaultTxid,
    required this.status,
    required this.ownerAddress,
    required this.termClass,
    required this.cents,
    required this.collateralZat,
    required this.lockHeight,
    required this.claimHeight,
    required this.mintHeight,
    required this.tip,
    required this.open,
    required this.redeemable,
    required this.blocksUntilRedeem,
    required this.releasable,
    required this.claimable,
    required this.underwaterAtMicroUsd,
    required this.underwater,
    required this.closeHeight,
    required this.closingTxid,
    required this.voidReason,
  });

  @override
  int get hashCode =>
      vaultTxid.hashCode ^
      status.hashCode ^
      ownerAddress.hashCode ^
      termClass.hashCode ^
      cents.hashCode ^
      collateralZat.hashCode ^
      lockHeight.hashCode ^
      claimHeight.hashCode ^
      mintHeight.hashCode ^
      tip.hashCode ^
      open.hashCode ^
      redeemable.hashCode ^
      blocksUntilRedeem.hashCode ^
      releasable.hashCode ^
      claimable.hashCode ^
      underwaterAtMicroUsd.hashCode ^
      underwater.hashCode ^
      closeHeight.hashCode ^
      closingTxid.hashCode ^
      voidReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultSummary &&
          runtimeType == other.runtimeType &&
          vaultTxid == other.vaultTxid &&
          status == other.status &&
          ownerAddress == other.ownerAddress &&
          termClass == other.termClass &&
          cents == other.cents &&
          collateralZat == other.collateralZat &&
          lockHeight == other.lockHeight &&
          claimHeight == other.claimHeight &&
          mintHeight == other.mintHeight &&
          tip == other.tip &&
          open == other.open &&
          redeemable == other.redeemable &&
          blocksUntilRedeem == other.blocksUntilRedeem &&
          releasable == other.releasable &&
          claimable == other.claimable &&
          underwaterAtMicroUsd == other.underwaterAtMicroUsd &&
          underwater == other.underwater &&
          closeHeight == other.closeHeight &&
          closingTxid == other.closingTxid &&
          voidReason == other.voidReason;
}

/// [`export_wif`].
class WifExport {
  /// The address, `ye…` form.
  final String addressYe;

  /// The address, `s…` form.
  final String addressS;

  /// The WIF (`dumpprivkey` format, D-W-11).
  final String wif;

  /// `false` for an imported key.
  final bool coveredBySeed;

  const WifExport({
    required this.addressYe,
    required this.addressS,
    required this.wif,
    required this.coveredBySeed,
  });

  @override
  int get hashCode =>
      addressYe.hashCode ^
      addressS.hashCode ^
      wif.hashCode ^
      coveredBySeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WifExport &&
          runtimeType == other.runtimeType &&
          addressYe == other.addressYe &&
          addressS == other.addressS &&
          wif == other.wif &&
          coveredBySeed == other.coveredBySeed;
}

/// The funding of a YEC send.
enum YecFunding {
  /// Transparent `YEC` (and, with `send_everything`, `FEE_RESERVE`) outputs.
  transparent,

  /// Private (Sapling) notes.
  shielded,
}

/// A YEC send, before confirmation.
class YecPreview {
  /// Pass to [`send_yec_confirm`].
  final String previewId;

  /// The recipient as given.
  final String to;

  /// The amount actually sent, zat.
  final PlatformInt64 amountZat;

  /// The amount was raised by one zat off `TOKEN_VALUE`.
  final bool amountBumped;

  /// The fee, zat.
  final PlatformInt64 feeZat;

  /// The change, zat.
  final PlatformInt64 changeZat;

  /// Number of inputs.
  final int inputs;

  /// The fee reserve was spent (`send_everything`).
  final bool usesReserve;

  /// YEC that stays reserved for YED fees after this send, zat.
  final PlatformInt64 keepsReservedZat;

  /// `nExpiryHeight`.
  final int expiryHeight;

  /// The txid the transaction will have (empty for a private send: its proofs are made at
  /// confirm, so the txid is known only then).
  final String txid;

  /// Where the money comes from (privacy first, `build::yec_private`).
  final YecFunding funding;

  /// Private funds go to a transparent address: the amber line "This send leaves the
  /// private pool".
  final bool revealsShielded;

  /// The memo that will be sent (private recipients only).
  final String? memo;

  /// A private send whose proving parameters are not downloaded yet: run
  /// [`download_params`] before [`send_yec_confirm`].
  final bool paramsNeeded;

  const YecPreview({
    required this.previewId,
    required this.to,
    required this.amountZat,
    required this.amountBumped,
    required this.feeZat,
    required this.changeZat,
    required this.inputs,
    required this.usesReserve,
    required this.keepsReservedZat,
    required this.expiryHeight,
    required this.txid,
    required this.funding,
    required this.revealsShielded,
    this.memo,
    required this.paramsNeeded,
  });

  @override
  int get hashCode =>
      previewId.hashCode ^
      to.hashCode ^
      amountZat.hashCode ^
      amountBumped.hashCode ^
      feeZat.hashCode ^
      changeZat.hashCode ^
      inputs.hashCode ^
      usesReserve.hashCode ^
      keepsReservedZat.hashCode ^
      expiryHeight.hashCode ^
      txid.hashCode ^
      funding.hashCode ^
      revealsShielded.hashCode ^
      memo.hashCode ^
      paramsNeeded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YecPreview &&
          runtimeType == other.runtimeType &&
          previewId == other.previewId &&
          to == other.to &&
          amountZat == other.amountZat &&
          amountBumped == other.amountBumped &&
          feeZat == other.feeZat &&
          changeZat == other.changeZat &&
          inputs == other.inputs &&
          usesReserve == other.usesReserve &&
          keepsReservedZat == other.keepsReservedZat &&
          expiryHeight == other.expiryHeight &&
          txid == other.txid &&
          funding == other.funding &&
          revealsShielded == other.revealsShielded &&
          memo == other.memo &&
          paramsNeeded == other.paramsNeeded;
}

/// A YED send, before confirmation.
class YedPreview {
  /// Pass to [`send_yed_confirm`].
  final String previewId;

  /// The recipients.
  final List<Recipient> recipients;

  /// Total cents to the recipients.
  final PlatformInt64 totalCents;

  /// The selection stage (`exact`, `single`, `greedy`, `search`).
  final String stage;

  /// Number of YED inputs.
  final int yedInputs;

  /// YED change, cents.
  final PlatformInt64 changeCents;

  /// Number of YEC inputs (fee).
  final int yecInputs;

  /// The fee, zat.
  final PlatformInt64 feeZat;

  /// YEC change, zat.
  final PlatformInt64 yecChangeZat;

  /// `nExpiryHeight`.
  final int expiryHeight;

  /// The txid the transaction will have.
  final String txid;

  /// The node's dry run on these bytes (the same rule the gate applies at confirm).
  final DryRun dryRun;

  const YedPreview({
    required this.previewId,
    required this.recipients,
    required this.totalCents,
    required this.stage,
    required this.yedInputs,
    required this.changeCents,
    required this.yecInputs,
    required this.feeZat,
    required this.yecChangeZat,
    required this.expiryHeight,
    required this.txid,
    required this.dryRun,
  });

  @override
  int get hashCode =>
      previewId.hashCode ^
      recipients.hashCode ^
      totalCents.hashCode ^
      stage.hashCode ^
      yedInputs.hashCode ^
      changeCents.hashCode ^
      yecInputs.hashCode ^
      feeZat.hashCode ^
      yecChangeZat.hashCode ^
      expiryHeight.hashCode ^
      txid.hashCode ^
      dryRun.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YedPreview &&
          runtimeType == other.runtimeType &&
          previewId == other.previewId &&
          recipients == other.recipients &&
          totalCents == other.totalCents &&
          stage == other.stage &&
          yedInputs == other.yedInputs &&
          changeCents == other.changeCents &&
          yecInputs == other.yecInputs &&
          feeZat == other.feeZat &&
          yecChangeZat == other.yecChangeZat &&
          expiryHeight == other.expiryHeight &&
          txid == other.txid &&
          dryRun == other.dryRun;
}

/// Yellowback availability on the server (contract rule 1).
class YellowbackStatus {
  /// The server offers the service (`GetYellowbackInfo` answered).
  final bool present;

  /// `enabled && active`: YED features may be shown.
  final bool usable;

  /// The `rpcversion` (0 when absent).
  final PlatformInt64 rpcversion;

  /// `enabled`.
  final bool enabled;

  /// `active`.
  final bool active;

  /// The server's Yellowback build string.
  final String serverVersion;

  /// The node's `feeZat` (0 when absent).
  final PlatformInt64 feeZat;

  const YellowbackStatus({
    required this.present,
    required this.usable,
    required this.rpcversion,
    required this.enabled,
    required this.active,
    required this.serverVersion,
    required this.feeZat,
  });

  @override
  int get hashCode =>
      present.hashCode ^
      usable.hashCode ^
      rpcversion.hashCode ^
      enabled.hashCode ^
      active.hashCode ^
      serverVersion.hashCode ^
      feeZat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YellowbackStatus &&
          runtimeType == other.runtimeType &&
          present == other.present &&
          usable == other.usable &&
          rpcversion == other.rpcversion &&
          enabled == other.enabled &&
          active == other.active &&
          serverVersion == other.serverVersion &&
          feeZat == other.feeZat;
}

/// The one error type of the surface. `message` is complete and showable as-is.
class YewError implements FrbException {
  /// The kind.
  final ErrorKind kind;

  /// The text to show.
  final String message;

  const YewError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YewError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}
