// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connect`, `ensure_conn`, `format_yec`, `from_network`, `gate_message`, `history_item`, `locked`, `new`, `not_yet`, `open_wallet`, `parse_server`, `runtime`, `sync`, `to_network`, `wallet_id`, `with_open_async`, `with_open`, `yellowback_status`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Conn`, `Open`, `Preview`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// The core's version.
String coreVersion() => RustLib.instance.api.crateApiCoreVersion();

/// A fresh BIP39 English mnemonic of 12 or 24 words (the app stores it in the keystore).
String generateSeedWords({required int words}) =>
    RustLib.instance.api.crateApiGenerateSeedWords(words: words);

/// Check a mnemonic without opening anything.
void checkSeedWords({required String seedWords}) =>
    RustLib.instance.api.crateApiCheckSeedWords(seedWords: seedWords);

/// Parse an address for `network` (the Send screen's field check).
AddressCheck validateAddress({
  required NetworkId network,
  required String address,
}) => RustLib.instance.api.crateApiValidateAddress(
  network: network,
  address: address,
);

/// Probe a server before any wallet is open (Onboarding's default birthday, Settings' server
/// check). Contract rule 1: an unknown `rpcversion` is an error.
Future<ServerProbe> probeServer({
  required String server,
  required bool plain,
  required NetworkId network,
}) => RustLib.instance.api.crateApiProbeServer(
  server: server,
  plain: plain,
  network: network,
);

/// Create (or restore) a wallet and open it. `seed_words` `None` generates a 12-word mnemonic
/// and returns it once in [`Created::seed_words`]. `birthday` `None` = from the first block
/// (pass the server's tip for a new seed). `data_dir` is the app's private directory.
Future<Created> createWallet({
  String? seedWords,
  required String passphrase,
  PlatformInt64? birthday,
  required NetworkId network,
  required String server,
  required bool plain,
  required String dataDir,
}) => RustLib.instance.api.crateApiCreateWallet(
  seedWords: seedWords,
  passphrase: passphrase,
  birthday: birthday,
  network: network,
  server: server,
  plain: plain,
  dataDir: dataDir,
);

/// Open an existing wallet with its seed (from the keystore). Returns the wallet id.
Future<String> unlock({
  required String seedWords,
  required String passphrase,
  required NetworkId network,
  required String server,
  required bool plain,
  required String dataDir,
}) => RustLib.instance.api.crateApiUnlock(
  seedWords: seedWords,
  passphrase: passphrase,
  network: network,
  server: server,
  plain: plain,
  dataDir: dataDir,
);

/// Drop the wallet handle, its derived keys, its connection and any preview.
Future<void> lock() => RustLib.instance.api.crateApiLock();

/// Is a wallet open?
bool isUnlocked() => RustLib.instance.api.crateApiIsUnlocked();

/// Change the server of the open wallet (Settings). The next call reconnects.
Future<void> setServer({required String server, required bool plain}) =>
    RustLib.instance.api.crateApiSetServer(server: server, plain: plain);

/// Server info, Yellowback info, tip, sync height (connects if needed).
Future<Status> status() => RustLib.instance.api.crateApiStatus();

/// The balances from the store (no network).
Future<Balances> balances() => RustLib.instance.api.crateApiBalances();

/// The receive address (first unused external). `fresh` marks the current one used first.
Future<AddressPair> receiveAddress({required bool fresh}) =>
    RustLib.instance.api.crateApiReceiveAddress(fresh: fresh);

/// Every address of the wallet (Settings → export private key picks one).
Future<List<AddressPair>> addresses() =>
    RustLib.instance.api.crateApiAddresses();

/// One page of history (pending first, then newest first). `page_size` 0 = 50.
Future<HistoryPage> history({required int page, required int pageSize}) =>
    RustLib.instance.api.crateApiHistory(page: page, pageSize: pageSize);

/// Build and sign a YEC send (after a sync). Nothing is broadcast.
Future<YecPreview> sendYecPreview({
  required String to,
  required PlatformInt64 zat,
  required bool sendEverything,
}) => RustLib.instance.api.crateApiSendYecPreview(
  to: to,
  zat: zat,
  sendEverything: sendEverything,
);

/// Broadcast a YEC preview through the gate (D-W-5).
Future<SendResult> sendYecConfirm({required String previewId}) =>
    RustLib.instance.api.crateApiSendYecConfirm(previewId: previewId);

/// Build and sign a YED transfer (after a sync) and dry-run it on the node. Nothing is
/// broadcast. With too little YEC for the fee the error is [`ErrorKind::NeedYecForFees`].
Future<YedPreview> sendYedPreview({required List<Recipient> recipients}) =>
    RustLib.instance.api.crateApiSendYedPreview(recipients: recipients);

/// Broadcast a YED preview through the gate (D-W-5): both layers again on the same bytes.
Future<SendResult> sendYedConfirm({required String previewId}) =>
    RustLib.instance.api.crateApiSendYedConfirm(previewId: previewId);

/// Export the WIF of an own address (D-W-11). The app shows the warning: YEC **and** YED on
/// this address move with the key.
Future<WifExport> exportWif({required String address}) =>
    RustLib.instance.api.crateApiExportWif(address: address);

/// Import a WIF (from YecWallet / `dumpprivkey`) as a key outside the HD tree (D-W-11).
/// `birthday` (the height to rescan from) lowers the wallet's scan floor so the next sync
/// finds the key's history. The key is not covered by the seed backup.
Future<AddressPair> importWif({required String wif, PlatformInt64? birthday}) =>
    RustLib.instance.api.crateApiImportWif(wif: wif, birthday: birthday);

/// Sync now, reporting progress on `sink` (Dart: a `Stream<SyncEvent>`), ending with `Done`
/// or `Failed`. The returned error mirrors the `Failed` event.
Stream<SyncEvent> syncNow() => RustLib.instance.api.crateApiSyncNow();

/// W4: the mint estimate.
Future<MintEstimate> mintEstimate({
  required PlatformInt64 cents,
  required int lockBlocks,
}) => RustLib.instance.api.crateApiMintEstimate(
  cents: cents,
  lockBlocks: lockBlocks,
);

/// W4: start a mint (the carrier step).
Future<MintState> mintStart({
  required PlatformInt64 cents,
  required int lockBlocks,
}) => RustLib.instance.api.crateApiMintStart(
  cents: cents,
  lockBlocks: lockBlocks,
);

/// W4: finish a mint (the main transaction).
Future<MintState> mintFinish({required String mintId}) =>
    RustLib.instance.api.crateApiMintFinish(mintId: mintId);

/// W4: sweep a lapsed carrier.
Future<MintState> mintSweep({required String mintId}) =>
    RustLib.instance.api.crateApiMintSweep(mintId: mintId);

/// W4: the vaults this wallet owns.
Future<List<VaultSummary>> vaults() => RustLib.instance.api.crateApiVaults();

/// W4: redeem a vault.
Future<SendResult> redeem({required String vaultTxid}) =>
    RustLib.instance.api.crateApiRedeem(vaultTxid: vaultTxid);

/// W4: the claimable vaults.
Future<List<VaultSummary>> claimable() =>
    RustLib.instance.api.crateApiClaimable();

/// W4: claim a vault.
Future<SendResult> claim({required String vaultTxid}) =>
    RustLib.instance.api.crateApiClaim(vaultTxid: vaultTxid);

/// [`validate_address`].
class AddressCheck {
  /// Parses for the network.
  final bool valid;

  /// `p2pkh` / `p2sh`, empty when invalid.
  final String kind;

  /// The `ye…` form was given.
  final bool yellowbackForm;

  /// Why it is invalid, empty when valid.
  final String message;

  const AddressCheck({
    required this.valid,
    required this.kind,
    required this.yellowbackForm,
    required this.message,
  });

  @override
  int get hashCode =>
      valid.hashCode ^
      kind.hashCode ^
      yellowbackForm.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressCheck &&
          runtimeType == other.runtimeType &&
          valid == other.valid &&
          kind == other.kind &&
          yellowbackForm == other.yellowbackForm &&
          message == other.message;
}

/// A receive address in both forms.
class AddressPair {
  /// The Yellowback form (`ye…` / `yt…` / `yr…`).
  final String ye;

  /// The transparent form (`s1…` / `sm…`).
  final String s;

  /// The derivation path, or `imported`.
  final String path;

  /// `false` for an imported key (not covered by the seed backup).
  final bool coveredBySeed;

  const AddressPair({
    required this.ye,
    required this.s,
    required this.path,
    required this.coveredBySeed,
  });

  @override
  int get hashCode =>
      ye.hashCode ^ s.hashCode ^ path.hashCode ^ coveredBySeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressPair &&
          runtimeType == other.runtimeType &&
          ye == other.ye &&
          s == other.s &&
          path == other.path &&
          coveredBySeed == other.coveredBySeed;
}

/// [`balances`] (plan §3.4 shape; computed from classes, §3.7).
class Balances {
  /// YEC available (class `YEC`), zat.
  final PlatformInt64 yecZat;

  /// YEC reserved for YED fees (class `FEE_RESERVE`), zat.
  final PlatformInt64 yecReservedZat;

  /// YEC change of own unconfirmed transactions, zat (in neither balance).
  final PlatformInt64 yecPendingZat;

  /// YED (class `TOKEN`), cents.
  final PlatformInt64 yedCents;

  /// Pending YED (class `PENDING_TOKEN`), cents.
  final PlatformInt64 yedPendingCents;

  /// `GetPrice.pMint` at the last sync, micro-USD per YEC; `None` when undefined.
  final PlatformInt64? priceMicroUsd;

  /// Outputs of `TOKEN_VALUE` the server does not list (class `HELD`): count.
  final PlatformInt64 heldCount;

  /// The height the wallet last synced to (0 = never).
  final PlatformInt64 syncHeight;

  /// The YEC a YED send needs at least (`fee + 2 · TOKEN_VALUE`), zat.
  final PlatformInt64 yedSendMinZat;

  const Balances({
    required this.yecZat,
    required this.yecReservedZat,
    required this.yecPendingZat,
    required this.yedCents,
    required this.yedPendingCents,
    this.priceMicroUsd,
    required this.heldCount,
    required this.syncHeight,
    required this.yedSendMinZat,
  });

  static Future<Balances> default_() =>
      RustLib.instance.api.crateApiBalancesDefault();

  @override
  int get hashCode =>
      yecZat.hashCode ^
      yecReservedZat.hashCode ^
      yecPendingZat.hashCode ^
      yedCents.hashCode ^
      yedPendingCents.hashCode ^
      priceMicroUsd.hashCode ^
      heldCount.hashCode ^
      syncHeight.hashCode ^
      yedSendMinZat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Balances &&
          runtimeType == other.runtimeType &&
          yecZat == other.yecZat &&
          yecReservedZat == other.yecReservedZat &&
          yecPendingZat == other.yecPendingZat &&
          yedCents == other.yedCents &&
          yedPendingCents == other.yedPendingCents &&
          priceMicroUsd == other.priceMicroUsd &&
          heldCount == other.heldCount &&
          syncHeight == other.syncHeight &&
          yedSendMinZat == other.yedSendMinZat;
}

/// The result of [`create_wallet`].
class Created {
  /// The wallet id (the primary address's key hash, hex-prefixed).
  final String walletId;

  /// The mnemonic, **only when this call generated it** (the app stores it in the platform
  /// keystore and shows it once for backup); `None` when the caller supplied the words.
  final String? seedWords;

  /// The primary receive address, `ye…` form.
  final String addressYe;

  const Created({
    required this.walletId,
    this.seedWords,
    required this.addressYe,
  });

  @override
  int get hashCode =>
      walletId.hashCode ^ seedWords.hashCode ^ addressYe.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Created &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          seedWords == other.seedWords &&
          addressYe == other.addressYe;
}

/// The node's dry run of a preview (`ValidateRawTransaction`).
class DryRun {
  /// `valid`.
  final bool valid;

  /// `verdict`.
  final String verdict;

  /// `burned`, cents.
  final PlatformInt64 burnedCents;

  /// `wouldBeRejected`.
  final bool wouldBeRejected;

  /// `yedIn`, cents.
  final PlatformInt64 yedInCents;

  /// `yedOut`, cents.
  final PlatformInt64 yedOutCents;

  /// `true` when the gate would accept this validation.
  final bool accepted;

  const DryRun({
    required this.valid,
    required this.verdict,
    required this.burnedCents,
    required this.wouldBeRejected,
    required this.yedInCents,
    required this.yedOutCents,
    required this.accepted,
  });

  @override
  int get hashCode =>
      valid.hashCode ^
      verdict.hashCode ^
      burnedCents.hashCode ^
      wouldBeRejected.hashCode ^
      yedInCents.hashCode ^
      yedOutCents.hashCode ^
      accepted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DryRun &&
          runtimeType == other.runtimeType &&
          valid == other.valid &&
          verdict == other.verdict &&
          burnedCents == other.burnedCents &&
          wouldBeRejected == other.wouldBeRejected &&
          yedInCents == other.yedInCents &&
          yedOutCents == other.yedOutCents &&
          accepted == other.accepted;
}

/// What kind of failure a [`YewError`] is; `message` is always the text to show.
enum ErrorKind {
  /// No wallet is open ([`unlock`] first).
  locked,

  /// A wallet is already open ([`lock`] first).
  alreadyOpen,

  /// A Phase W4 call.
  notYetImplemented,

  /// The broadcast gate refused (the node's verdict is in `message`, D-W-5).
  gate,

  /// The server could not be reached or answered with an error.
  network,

  /// The server offers no usable Yellowback service (contract rule 1).
  yellowbackUnavailable,

  /// The builder refused (`change-floor`, `insufficient-yed`, bad address, ...).
  refused,

  /// Not enough YEC for the fee of a YED operation (§3.7 item 4).
  needYecForFees,

  /// Bad input from the app (mnemonic, address, WIF, amount).
  input,

  /// A preview id that no longer exists.
  previewExpired,

  /// Anything else (storage, key derivation).
  other,
}

/// One history row.
class HistoryItem {
  /// Txid, display form.
  final String txid;

  /// Block height (0 while pending).
  final PlatformInt64 height;

  /// Unconfirmed.
  final bool pending;

  /// Net YEC, zat (negative = sent).
  final PlatformInt64 yecDeltaZat;

  /// Net YED, cents (negative = sent).
  final PlatformInt64 yedDeltaCents;

  /// The verdict-derived label (`received $12.34`, `sent $12.34`, `minted $…`, ...), or the
  /// CLI's fallbacks for an unlabelled payload.
  final String label;

  /// The node's verdict, when known.
  final String verdict;

  /// The Yellowback kind (`transfer`, `mint`, ...), when known.
  final String kind;

  /// The transaction carries an `OP_RETURN`.
  final bool hasPayload;

  /// The transaction has shielded components (a transparent leg of a shielded tx).
  final bool shielded;

  const HistoryItem({
    required this.txid,
    required this.height,
    required this.pending,
    required this.yecDeltaZat,
    required this.yedDeltaCents,
    required this.label,
    required this.verdict,
    required this.kind,
    required this.hasPayload,
    required this.shielded,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      height.hashCode ^
      pending.hashCode ^
      yecDeltaZat.hashCode ^
      yedDeltaCents.hashCode ^
      label.hashCode ^
      verdict.hashCode ^
      kind.hashCode ^
      hasPayload.hashCode ^
      shielded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryItem &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          height == other.height &&
          pending == other.pending &&
          yecDeltaZat == other.yecDeltaZat &&
          yedDeltaCents == other.yedDeltaCents &&
          label == other.label &&
          verdict == other.verdict &&
          kind == other.kind &&
          hasPayload == other.hasPayload &&
          shielded == other.shielded;
}

/// One page of [`history`].
class HistoryPage {
  /// The rows of this page, pending first then newest first.
  final List<HistoryItem> rows;

  /// The page index requested.
  final int page;

  /// Total rows.
  final PlatformInt64 total;

  const HistoryPage({
    required this.rows,
    required this.page,
    required this.total,
  });

  @override
  int get hashCode => rows.hashCode ^ page.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryPage &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          page == other.page &&
          total == other.total;
}

/// Placeholder for the W4 mint estimate.
class MintEstimate {
  /// Cents to mint.
  final PlatformInt64 cents;

  /// Required YEC collateral, zat.
  final PlatformInt64 collateralZat;

  const MintEstimate({required this.cents, required this.collateralZat});

  @override
  int get hashCode => cents.hashCode ^ collateralZat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintEstimate &&
          runtimeType == other.runtimeType &&
          cents == other.cents &&
          collateralZat == other.collateralZat;
}

/// Placeholder for the W4 mint state.
class MintState {
  /// The mint id.
  final String mintId;

  /// The state name.
  final String state;

  const MintState({required this.mintId, required this.state});

  @override
  int get hashCode => mintId.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintState &&
          runtimeType == other.runtimeType &&
          mintId == other.mintId &&
          state == other.state;
}

/// The network a wallet is for.
enum NetworkId {
  /// Regtest (the devnet).
  regtest,

  /// Testnet.
  testnet,

  /// Mainnet.
  mainnet,
}

/// One recipient of a YED send.
class Recipient {
  /// `ye…` / `yr…` / `s…`.
  final String address;

  /// Cents.
  final PlatformInt64 cents;

  const Recipient({required this.address, required this.cents});

  @override
  int get hashCode => address.hashCode ^ cents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Recipient &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          cents == other.cents;
}

/// The result of a confirm.
class SendResult {
  /// The txid, display form.
  final String txid;

  /// The node's verdict on the broadcast bytes (`ok`), empty on the YEC path against a
  /// server without Yellowback.
  final String verdict;

  const SendResult({required this.txid, required this.verdict});

  @override
  int get hashCode => txid.hashCode ^ verdict.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendResult &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          verdict == other.verdict;
}

/// [`probe_server`]: what a server answers before any wallet is open.
class ServerProbe {
  /// The server's `version`.
  final String serverVersion;

  /// The server's chain name.
  final String chainName;

  /// The tip (the default birthday of a new wallet).
  final PlatformInt64 tip;

  /// `taddrSupport`.
  final bool taddrSupport;

  /// Yellowback on this server.
  final YellowbackStatus yellowback;

  const ServerProbe({
    required this.serverVersion,
    required this.chainName,
    required this.tip,
    required this.taddrSupport,
    required this.yellowback,
  });

  @override
  int get hashCode =>
      serverVersion.hashCode ^
      chainName.hashCode ^
      tip.hashCode ^
      taddrSupport.hashCode ^
      yellowback.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerProbe &&
          runtimeType == other.runtimeType &&
          serverVersion == other.serverVersion &&
          chainName == other.chainName &&
          tip == other.tip &&
          taddrSupport == other.taddrSupport &&
          yellowback == other.yellowback;
}

/// [`status`]: the open wallet and its server.
class Status {
  /// The wallet id.
  final String walletId;

  /// The network.
  final NetworkId network;

  /// `host:port`.
  final String server;

  /// Plain HTTP/2 (regtest only).
  final bool plain;

  /// The server's `version`.
  final String serverVersion;

  /// The server's chain name.
  final String chainName;

  /// `consensusBranchId`, hex.
  final String branchId;

  /// The tip.
  final PlatformInt64 tip;

  /// The wallet's birthday height.
  final PlatformInt64 birthday;

  /// The height the wallet last synced to (0 = never).
  final PlatformInt64 syncHeight;

  /// The number of addresses the wallet watches.
  final PlatformInt64 addresses;

  /// Yellowback on this server.
  final YellowbackStatus yellowback;

  /// The core's version.
  final String coreVersion;

  const Status({
    required this.walletId,
    required this.network,
    required this.server,
    required this.plain,
    required this.serverVersion,
    required this.chainName,
    required this.branchId,
    required this.tip,
    required this.birthday,
    required this.syncHeight,
    required this.addresses,
    required this.yellowback,
    required this.coreVersion,
  });

  @override
  int get hashCode =>
      walletId.hashCode ^
      network.hashCode ^
      server.hashCode ^
      plain.hashCode ^
      serverVersion.hashCode ^
      chainName.hashCode ^
      branchId.hashCode ^
      tip.hashCode ^
      birthday.hashCode ^
      syncHeight.hashCode ^
      addresses.hashCode ^
      yellowback.hashCode ^
      coreVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Status &&
          runtimeType == other.runtimeType &&
          walletId == other.walletId &&
          network == other.network &&
          server == other.server &&
          plain == other.plain &&
          serverVersion == other.serverVersion &&
          chainName == other.chainName &&
          branchId == other.branchId &&
          tip == other.tip &&
          birthday == other.birthday &&
          syncHeight == other.syncHeight &&
          addresses == other.addresses &&
          yellowback == other.yellowback &&
          coreVersion == other.coreVersion;
}

/// One event of [`sync_now`].
class SyncEvent {
  /// The stage.
  final SyncStage stage;

  /// A one-line description (or the error on `Failed`).
  final String message;

  /// The tip (from `Probing` on).
  final PlatformInt64 tip;

  /// The height synced to (`Done`).
  final PlatformInt64 syncHeight;

  /// Yellowback usable on this server (from `Probing` on).
  final bool yellowbackUsable;

  const SyncEvent({
    required this.stage,
    required this.message,
    required this.tip,
    required this.syncHeight,
    required this.yellowbackUsable,
  });

  @override
  int get hashCode =>
      stage.hashCode ^
      message.hashCode ^
      tip.hashCode ^
      syncHeight.hashCode ^
      yellowbackUsable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncEvent &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          message == other.message &&
          tip == other.tip &&
          syncHeight == other.syncHeight &&
          yellowbackUsable == other.yellowbackUsable;
}

/// A stage of [`sync_now`].
enum SyncStage {
  /// Opening the channel.
  connecting,

  /// `GetLightdInfo` + `GetYellowbackInfo`.
  probing,

  /// The §3.2 loop.
  scanning,

  /// Finished; `tip` and `sync_height` are set.
  done,

  /// Failed; `message` is set.
  failed,
}

/// Placeholder for a W4 vault.
class VaultSummary {
  /// The vault txid.
  final String vaultTxid;

  /// Cents minted.
  final PlatformInt64 cents;

  /// Collateral, zat.
  final PlatformInt64 collateralZat;

  /// Lock height.
  final PlatformInt64 lockHeight;

  /// The status.
  final String status;

  const VaultSummary({
    required this.vaultTxid,
    required this.cents,
    required this.collateralZat,
    required this.lockHeight,
    required this.status,
  });

  @override
  int get hashCode =>
      vaultTxid.hashCode ^
      cents.hashCode ^
      collateralZat.hashCode ^
      lockHeight.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultSummary &&
          runtimeType == other.runtimeType &&
          vaultTxid == other.vaultTxid &&
          cents == other.cents &&
          collateralZat == other.collateralZat &&
          lockHeight == other.lockHeight &&
          status == other.status;
}

/// [`export_wif`].
class WifExport {
  /// The address, `ye…` form.
  final String addressYe;

  /// The address, `s…` form.
  final String addressS;

  /// The WIF (`dumpprivkey` format, D-W-11).
  final String wif;

  /// `false` for an imported key.
  final bool coveredBySeed;

  const WifExport({
    required this.addressYe,
    required this.addressS,
    required this.wif,
    required this.coveredBySeed,
  });

  @override
  int get hashCode =>
      addressYe.hashCode ^
      addressS.hashCode ^
      wif.hashCode ^
      coveredBySeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WifExport &&
          runtimeType == other.runtimeType &&
          addressYe == other.addressYe &&
          addressS == other.addressS &&
          wif == other.wif &&
          coveredBySeed == other.coveredBySeed;
}

/// A YEC send, before confirmation.
class YecPreview {
  /// Pass to [`send_yec_confirm`].
  final String previewId;

  /// The recipient as given.
  final String to;

  /// The amount actually sent, zat.
  final PlatformInt64 amountZat;

  /// The amount was raised by one zat off `TOKEN_VALUE`.
  final bool amountBumped;

  /// The fee, zat.
  final PlatformInt64 feeZat;

  /// The change, zat.
  final PlatformInt64 changeZat;

  /// Number of inputs.
  final int inputs;

  /// The fee reserve was spent (`send_everything`).
  final bool usesReserve;

  /// YEC that stays reserved for YED fees after this send, zat.
  final PlatformInt64 keepsReservedZat;

  /// `nExpiryHeight`.
  final int expiryHeight;

  /// The txid the transaction will have.
  final String txid;

  const YecPreview({
    required this.previewId,
    required this.to,
    required this.amountZat,
    required this.amountBumped,
    required this.feeZat,
    required this.changeZat,
    required this.inputs,
    required this.usesReserve,
    required this.keepsReservedZat,
    required this.expiryHeight,
    required this.txid,
  });

  @override
  int get hashCode =>
      previewId.hashCode ^
      to.hashCode ^
      amountZat.hashCode ^
      amountBumped.hashCode ^
      feeZat.hashCode ^
      changeZat.hashCode ^
      inputs.hashCode ^
      usesReserve.hashCode ^
      keepsReservedZat.hashCode ^
      expiryHeight.hashCode ^
      txid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YecPreview &&
          runtimeType == other.runtimeType &&
          previewId == other.previewId &&
          to == other.to &&
          amountZat == other.amountZat &&
          amountBumped == other.amountBumped &&
          feeZat == other.feeZat &&
          changeZat == other.changeZat &&
          inputs == other.inputs &&
          usesReserve == other.usesReserve &&
          keepsReservedZat == other.keepsReservedZat &&
          expiryHeight == other.expiryHeight &&
          txid == other.txid;
}

/// A YED send, before confirmation.
class YedPreview {
  /// Pass to [`send_yed_confirm`].
  final String previewId;

  /// The recipients.
  final List<Recipient> recipients;

  /// Total cents to the recipients.
  final PlatformInt64 totalCents;

  /// The selection stage (`exact`, `single`, `greedy`, `search`).
  final String stage;

  /// Number of YED inputs.
  final int yedInputs;

  /// YED change, cents.
  final PlatformInt64 changeCents;

  /// Number of YEC inputs (fee).
  final int yecInputs;

  /// The fee, zat.
  final PlatformInt64 feeZat;

  /// YEC change, zat.
  final PlatformInt64 yecChangeZat;

  /// `nExpiryHeight`.
  final int expiryHeight;

  /// The txid the transaction will have.
  final String txid;

  /// The node's dry run on these bytes (the same rule the gate applies at confirm).
  final DryRun dryRun;

  const YedPreview({
    required this.previewId,
    required this.recipients,
    required this.totalCents,
    required this.stage,
    required this.yedInputs,
    required this.changeCents,
    required this.yecInputs,
    required this.feeZat,
    required this.yecChangeZat,
    required this.expiryHeight,
    required this.txid,
    required this.dryRun,
  });

  @override
  int get hashCode =>
      previewId.hashCode ^
      recipients.hashCode ^
      totalCents.hashCode ^
      stage.hashCode ^
      yedInputs.hashCode ^
      changeCents.hashCode ^
      yecInputs.hashCode ^
      feeZat.hashCode ^
      yecChangeZat.hashCode ^
      expiryHeight.hashCode ^
      txid.hashCode ^
      dryRun.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YedPreview &&
          runtimeType == other.runtimeType &&
          previewId == other.previewId &&
          recipients == other.recipients &&
          totalCents == other.totalCents &&
          stage == other.stage &&
          yedInputs == other.yedInputs &&
          changeCents == other.changeCents &&
          yecInputs == other.yecInputs &&
          feeZat == other.feeZat &&
          yecChangeZat == other.yecChangeZat &&
          expiryHeight == other.expiryHeight &&
          txid == other.txid &&
          dryRun == other.dryRun;
}

/// Yellowback availability on the server (contract rule 1).
class YellowbackStatus {
  /// The server offers the service (`GetYellowbackInfo` answered).
  final bool present;

  /// `enabled && active`: YED features may be shown.
  final bool usable;

  /// The `rpcversion` (0 when absent).
  final PlatformInt64 rpcversion;

  /// `enabled`.
  final bool enabled;

  /// `active`.
  final bool active;

  /// The server's Yellowback build string.
  final String serverVersion;

  /// The node's `feeZat` (0 when absent).
  final PlatformInt64 feeZat;

  const YellowbackStatus({
    required this.present,
    required this.usable,
    required this.rpcversion,
    required this.enabled,
    required this.active,
    required this.serverVersion,
    required this.feeZat,
  });

  @override
  int get hashCode =>
      present.hashCode ^
      usable.hashCode ^
      rpcversion.hashCode ^
      enabled.hashCode ^
      active.hashCode ^
      serverVersion.hashCode ^
      feeZat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YellowbackStatus &&
          runtimeType == other.runtimeType &&
          present == other.present &&
          usable == other.usable &&
          rpcversion == other.rpcversion &&
          enabled == other.enabled &&
          active == other.active &&
          serverVersion == other.serverVersion &&
          feeZat == other.feeZat;
}

/// The one error type of the surface. `message` is complete and showable as-is.
class YewError implements FrbException {
  /// The kind.
  final ErrorKind kind;

  /// The text to show.
  final String message;

  const YewError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YewError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}
