// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<SyncEvent> dco_decode_StreamSink_sync_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddressCheck dco_decode_address_check(dynamic raw);

  @protected
  AddressPair dco_decode_address_pair(dynamic raw);

  @protected
  Balances dco_decode_balances(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ClaimableItem dco_decode_claimable_item(dynamic raw);

  @protected
  Created dco_decode_created(dynamic raw);

  @protected
  DefaultEndpoint dco_decode_default_endpoint(dynamic raw);

  @protected
  DryRun dco_decode_dry_run(dynamic raw);

  @protected
  ErrorKind dco_decode_error_kind(dynamic raw);

  @protected
  HistoryItem dco_decode_history_item(dynamic raw);

  @protected
  HistoryPage dco_decode_history_page(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<AddressPair> dco_decode_list_address_pair(dynamic raw);

  @protected
  List<ClaimableItem> dco_decode_list_claimable_item(dynamic raw);

  @protected
  List<DefaultEndpoint> dco_decode_list_default_endpoint(dynamic raw);

  @protected
  List<HistoryItem> dco_decode_list_history_item(dynamic raw);

  @protected
  List<MintStatus> dco_decode_list_mint_status(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Recipient> dco_decode_list_recipient(dynamic raw);

  @protected
  List<VaultSummary> dco_decode_list_vault_summary(dynamic raw);

  @protected
  MintEstimate dco_decode_mint_estimate(dynamic raw);

  @protected
  MintStatus dco_decode_mint_status(dynamic raw);

  @protected
  NetworkId dco_decode_network_id(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  Recipient dco_decode_recipient(dynamic raw);

  @protected
  RedeemResult dco_decode_redeem_result(dynamic raw);

  @protected
  SendResult dco_decode_send_result(dynamic raw);

  @protected
  ServerProbe dco_decode_server_probe(dynamic raw);

  @protected
  Status dco_decode_status(dynamic raw);

  @protected
  SyncEvent dco_decode_sync_event(dynamic raw);

  @protected
  SyncStage dco_decode_sync_stage(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VaultSummary dco_decode_vault_summary(dynamic raw);

  @protected
  WifExport dco_decode_wif_export(dynamic raw);

  @protected
  YecPreview dco_decode_yec_preview(dynamic raw);

  @protected
  YedPreview dco_decode_yed_preview(dynamic raw);

  @protected
  YellowbackStatus dco_decode_yellowback_status(dynamic raw);

  @protected
  YewError dco_decode_yew_error(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<SyncEvent> sse_decode_StreamSink_sync_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddressCheck sse_decode_address_check(SseDeserializer deserializer);

  @protected
  AddressPair sse_decode_address_pair(SseDeserializer deserializer);

  @protected
  Balances sse_decode_balances(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ClaimableItem sse_decode_claimable_item(SseDeserializer deserializer);

  @protected
  Created sse_decode_created(SseDeserializer deserializer);

  @protected
  DefaultEndpoint sse_decode_default_endpoint(SseDeserializer deserializer);

  @protected
  DryRun sse_decode_dry_run(SseDeserializer deserializer);

  @protected
  ErrorKind sse_decode_error_kind(SseDeserializer deserializer);

  @protected
  HistoryItem sse_decode_history_item(SseDeserializer deserializer);

  @protected
  HistoryPage sse_decode_history_page(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<AddressPair> sse_decode_list_address_pair(SseDeserializer deserializer);

  @protected
  List<ClaimableItem> sse_decode_list_claimable_item(
    SseDeserializer deserializer,
  );

  @protected
  List<DefaultEndpoint> sse_decode_list_default_endpoint(
    SseDeserializer deserializer,
  );

  @protected
  List<HistoryItem> sse_decode_list_history_item(SseDeserializer deserializer);

  @protected
  List<MintStatus> sse_decode_list_mint_status(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Recipient> sse_decode_list_recipient(SseDeserializer deserializer);

  @protected
  List<VaultSummary> sse_decode_list_vault_summary(
    SseDeserializer deserializer,
  );

  @protected
  MintEstimate sse_decode_mint_estimate(SseDeserializer deserializer);

  @protected
  MintStatus sse_decode_mint_status(SseDeserializer deserializer);

  @protected
  NetworkId sse_decode_network_id(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Recipient sse_decode_recipient(SseDeserializer deserializer);

  @protected
  RedeemResult sse_decode_redeem_result(SseDeserializer deserializer);

  @protected
  SendResult sse_decode_send_result(SseDeserializer deserializer);

  @protected
  ServerProbe sse_decode_server_probe(SseDeserializer deserializer);

  @protected
  Status sse_decode_status(SseDeserializer deserializer);

  @protected
  SyncEvent sse_decode_sync_event(SseDeserializer deserializer);

  @protected
  SyncStage sse_decode_sync_stage(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VaultSummary sse_decode_vault_summary(SseDeserializer deserializer);

  @protected
  WifExport sse_decode_wif_export(SseDeserializer deserializer);

  @protected
  YecPreview sse_decode_yec_preview(SseDeserializer deserializer);

  @protected
  YedPreview sse_decode_yed_preview(SseDeserializer deserializer);

  @protected
  YellowbackStatus sse_decode_yellowback_status(SseDeserializer deserializer);

  @protected
  YewError sse_decode_yew_error(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_event_Sse(
    RustStreamSink<SyncEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_address_check(AddressCheck self, SseSerializer serializer);

  @protected
  void sse_encode_address_pair(AddressPair self, SseSerializer serializer);

  @protected
  void sse_encode_balances(Balances self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_claimable_item(ClaimableItem self, SseSerializer serializer);

  @protected
  void sse_encode_created(Created self, SseSerializer serializer);

  @protected
  void sse_encode_default_endpoint(
    DefaultEndpoint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dry_run(DryRun self, SseSerializer serializer);

  @protected
  void sse_encode_error_kind(ErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_history_item(HistoryItem self, SseSerializer serializer);

  @protected
  void sse_encode_history_page(HistoryPage self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_address_pair(
    List<AddressPair> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_claimable_item(
    List<ClaimableItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_default_endpoint(
    List<DefaultEndpoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_history_item(
    List<HistoryItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mint_status(
    List<MintStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_recipient(
    List<Recipient> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vault_summary(
    List<VaultSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mint_estimate(MintEstimate self, SseSerializer serializer);

  @protected
  void sse_encode_mint_status(MintStatus self, SseSerializer serializer);

  @protected
  void sse_encode_network_id(NetworkId self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recipient(Recipient self, SseSerializer serializer);

  @protected
  void sse_encode_redeem_result(RedeemResult self, SseSerializer serializer);

  @protected
  void sse_encode_send_result(SendResult self, SseSerializer serializer);

  @protected
  void sse_encode_server_probe(ServerProbe self, SseSerializer serializer);

  @protected
  void sse_encode_status(Status self, SseSerializer serializer);

  @protected
  void sse_encode_sync_event(SyncEvent self, SseSerializer serializer);

  @protected
  void sse_encode_sync_stage(SyncStage self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vault_summary(VaultSummary self, SseSerializer serializer);

  @protected
  void sse_encode_wif_export(WifExport self, SseSerializer serializer);

  @protected
  void sse_encode_yec_preview(YecPreview self, SseSerializer serializer);

  @protected
  void sse_encode_yed_preview(YedPreview self, SseSerializer serializer);

  @protected
  void sse_encode_yellowback_status(
    YellowbackStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_yew_error(YewError self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
