// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1836313511;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'yew_core',
        ioDirectory: '../core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<AddressPair>> crateApiAddresses();

  Future<Balances> crateApiBalances();

  Future<Balances> crateApiBalancesDefault();

  void crateApiCheckSeedWords({required String seedWords});

  Future<SendResult> crateApiClaim({required String vaultTxid});

  Future<List<VaultSummary>> crateApiClaimable();

  String crateApiCoreVersion();

  Future<Created> crateApiCreateWallet({
    String? seedWords,
    required String passphrase,
    PlatformInt64? birthday,
    required NetworkId network,
    required String server,
    required bool plain,
    required String dataDir,
  });

  Future<WifExport> crateApiExportWif({required String address});

  String crateApiGenerateSeedWords({required int words});

  Future<HistoryPage> crateApiHistory({
    required int page,
    required int pageSize,
  });

  Future<AddressPair> crateApiImportWif({
    required String wif,
    PlatformInt64? birthday,
  });

  Future<void> crateApiInitApp();

  bool crateApiIsUnlocked();

  Future<void> crateApiLock();

  Future<MintEstimate> crateApiMintEstimate({
    required PlatformInt64 cents,
    required int lockBlocks,
  });

  Future<MintState> crateApiMintFinish({required String mintId});

  Future<MintState> crateApiMintStart({
    required PlatformInt64 cents,
    required int lockBlocks,
  });

  Future<MintState> crateApiMintSweep({required String mintId});

  Future<ServerProbe> crateApiProbeServer({
    required String server,
    required bool plain,
    required NetworkId network,
  });

  Future<AddressPair> crateApiReceiveAddress({required bool fresh});

  Future<SendResult> crateApiRedeem({required String vaultTxid});

  Future<SendResult> crateApiSendYecConfirm({required String previewId});

  Future<YecPreview> crateApiSendYecPreview({
    required String to,
    required PlatformInt64 zat,
    required bool sendEverything,
  });

  Future<SendResult> crateApiSendYedConfirm({required String previewId});

  Future<YedPreview> crateApiSendYedPreview({
    required List<Recipient> recipients,
  });

  Future<void> crateApiSetServer({required String server, required bool plain});

  Future<Status> crateApiStatus();

  Stream<SyncEvent> crateApiSyncNow();

  Future<String> crateApiUnlock({
    required String seedWords,
    required String passphrase,
    required NetworkId network,
    required String server,
    required bool plain,
    required String dataDir,
  });

  AddressCheck crateApiValidateAddress({
    required NetworkId network,
    required String address,
  });

  Future<List<VaultSummary>> crateApiVaults();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<AddressPair>> crateApiAddresses() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_address_pair,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiAddressesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddressesConstMeta =>
      const TaskConstMeta(debugName: "addresses", argNames: []);

  @override
  Future<Balances> crateApiBalances() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_balances,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiBalancesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBalancesConstMeta =>
      const TaskConstMeta(debugName: "balances", argNames: []);

  @override
  Future<Balances> crateApiBalancesDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_balances,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBalancesDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBalancesDefaultConstMeta =>
      const TaskConstMeta(debugName: "balances_default", argNames: []);

  @override
  void crateApiCheckSeedWords({required String seedWords}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(seedWords, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiCheckSeedWordsConstMeta,
        argValues: [seedWords],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCheckSeedWordsConstMeta => const TaskConstMeta(
    debugName: "check_seed_words",
    argNames: ["seedWords"],
  );

  @override
  Future<SendResult> crateApiClaim({required String vaultTxid}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultTxid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_result,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiClaimConstMeta,
        argValues: [vaultTxid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClaimConstMeta =>
      const TaskConstMeta(debugName: "claim", argNames: ["vaultTxid"]);

  @override
  Future<List<VaultSummary>> crateApiClaimable() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_vault_summary,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiClaimableConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClaimableConstMeta =>
      const TaskConstMeta(debugName: "claimable", argNames: []);

  @override
  String crateApiCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "core_version", argNames: []);

  @override
  Future<Created> crateApiCreateWallet({
    String? seedWords,
    required String passphrase,
    PlatformInt64? birthday,
    required NetworkId network,
    required String server,
    required bool plain,
    required String dataDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(seedWords, serializer);
          sse_encode_String(passphrase, serializer);
          sse_encode_opt_box_autoadd_i_64(birthday, serializer);
          sse_encode_network_id(network, serializer);
          sse_encode_String(server, serializer);
          sse_encode_bool(plain, serializer);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_created,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiCreateWalletConstMeta,
        argValues: [
          seedWords,
          passphrase,
          birthday,
          network,
          server,
          plain,
          dataDir,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateWalletConstMeta => const TaskConstMeta(
    debugName: "create_wallet",
    argNames: [
      "seedWords",
      "passphrase",
      "birthday",
      "network",
      "server",
      "plain",
      "dataDir",
    ],
  );

  @override
  Future<WifExport> crateApiExportWif({required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wif_export,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiExportWifConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportWifConstMeta =>
      const TaskConstMeta(debugName: "export_wif", argNames: ["address"]);

  @override
  String crateApiGenerateSeedWords({required int words}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(words, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiGenerateSeedWordsConstMeta,
        argValues: [words],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateSeedWordsConstMeta => const TaskConstMeta(
    debugName: "generate_seed_words",
    argNames: ["words"],
  );

  @override
  Future<HistoryPage> crateApiHistory({
    required int page,
    required int pageSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(page, serializer);
          sse_encode_u_32(pageSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_history_page,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiHistoryConstMeta,
        argValues: [page, pageSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryConstMeta =>
      const TaskConstMeta(debugName: "history", argNames: ["page", "pageSize"]);

  @override
  Future<AddressPair> crateApiImportWif({
    required String wif,
    PlatformInt64? birthday,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wif, serializer);
          sse_encode_opt_box_autoadd_i_64(birthday, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_address_pair,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiImportWifConstMeta,
        argValues: [wif, birthday],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportWifConstMeta => const TaskConstMeta(
    debugName: "import_wif",
    argNames: ["wif", "birthday"],
  );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiIsUnlocked() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIsUnlockedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIsUnlockedConstMeta =>
      const TaskConstMeta(debugName: "is_unlocked", argNames: []);

  @override
  Future<void> crateApiLock() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLockConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLockConstMeta =>
      const TaskConstMeta(debugName: "lock", argNames: []);

  @override
  Future<MintEstimate> crateApiMintEstimate({
    required PlatformInt64 cents,
    required int lockBlocks,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(cents, serializer);
          sse_encode_u_32(lockBlocks, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mint_estimate,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiMintEstimateConstMeta,
        argValues: [cents, lockBlocks],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMintEstimateConstMeta => const TaskConstMeta(
    debugName: "mint_estimate",
    argNames: ["cents", "lockBlocks"],
  );

  @override
  Future<MintState> crateApiMintFinish({required String mintId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mintId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mint_state,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiMintFinishConstMeta,
        argValues: [mintId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMintFinishConstMeta =>
      const TaskConstMeta(debugName: "mint_finish", argNames: ["mintId"]);

  @override
  Future<MintState> crateApiMintStart({
    required PlatformInt64 cents,
    required int lockBlocks,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(cents, serializer);
          sse_encode_u_32(lockBlocks, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mint_state,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiMintStartConstMeta,
        argValues: [cents, lockBlocks],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMintStartConstMeta => const TaskConstMeta(
    debugName: "mint_start",
    argNames: ["cents", "lockBlocks"],
  );

  @override
  Future<MintState> crateApiMintSweep({required String mintId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mintId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mint_state,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiMintSweepConstMeta,
        argValues: [mintId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMintSweepConstMeta =>
      const TaskConstMeta(debugName: "mint_sweep", argNames: ["mintId"]);

  @override
  Future<ServerProbe> crateApiProbeServer({
    required String server,
    required bool plain,
    required NetworkId network,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(server, serializer);
          sse_encode_bool(plain, serializer);
          sse_encode_network_id(network, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_server_probe,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiProbeServerConstMeta,
        argValues: [server, plain, network],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProbeServerConstMeta => const TaskConstMeta(
    debugName: "probe_server",
    argNames: ["server", "plain", "network"],
  );

  @override
  Future<AddressPair> crateApiReceiveAddress({required bool fresh}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(fresh, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_address_pair,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiReceiveAddressConstMeta,
        argValues: [fresh],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiveAddressConstMeta =>
      const TaskConstMeta(debugName: "receive_address", argNames: ["fresh"]);

  @override
  Future<SendResult> crateApiRedeem({required String vaultTxid}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultTxid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_result,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiRedeemConstMeta,
        argValues: [vaultTxid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRedeemConstMeta =>
      const TaskConstMeta(debugName: "redeem", argNames: ["vaultTxid"]);

  @override
  Future<SendResult> crateApiSendYecConfirm({required String previewId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(previewId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_result,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiSendYecConfirmConstMeta,
        argValues: [previewId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendYecConfirmConstMeta => const TaskConstMeta(
    debugName: "send_yec_confirm",
    argNames: ["previewId"],
  );

  @override
  Future<YecPreview> crateApiSendYecPreview({
    required String to,
    required PlatformInt64 zat,
    required bool sendEverything,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(to, serializer);
          sse_encode_i_64(zat, serializer);
          sse_encode_bool(sendEverything, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_yec_preview,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiSendYecPreviewConstMeta,
        argValues: [to, zat, sendEverything],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendYecPreviewConstMeta => const TaskConstMeta(
    debugName: "send_yec_preview",
    argNames: ["to", "zat", "sendEverything"],
  );

  @override
  Future<SendResult> crateApiSendYedConfirm({required String previewId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(previewId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_result,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiSendYedConfirmConstMeta,
        argValues: [previewId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendYedConfirmConstMeta => const TaskConstMeta(
    debugName: "send_yed_confirm",
    argNames: ["previewId"],
  );

  @override
  Future<YedPreview> crateApiSendYedPreview({
    required List<Recipient> recipients,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_recipient(recipients, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_yed_preview,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiSendYedPreviewConstMeta,
        argValues: [recipients],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendYedPreviewConstMeta => const TaskConstMeta(
    debugName: "send_yed_preview",
    argNames: ["recipients"],
  );

  @override
  Future<void> crateApiSetServer({
    required String server,
    required bool plain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(server, serializer);
          sse_encode_bool(plain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiSetServerConstMeta,
        argValues: [server, plain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetServerConstMeta => const TaskConstMeta(
    debugName: "set_server",
    argNames: ["server", "plain"],
  );

  @override
  Future<Status> crateApiStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_status,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatusConstMeta =>
      const TaskConstMeta(debugName: "status", argNames: []);

  @override
  Stream<SyncEvent> crateApiSyncNow() {
    final sink = RustStreamSink<SyncEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_sync_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 29,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_yew_error,
          ),
          constMeta: kCrateApiSyncNowConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSyncNowConstMeta =>
      const TaskConstMeta(debugName: "sync_now", argNames: ["sink"]);

  @override
  Future<String> crateApiUnlock({
    required String seedWords,
    required String passphrase,
    required NetworkId network,
    required String server,
    required bool plain,
    required String dataDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(seedWords, serializer);
          sse_encode_String(passphrase, serializer);
          sse_encode_network_id(network, serializer);
          sse_encode_String(server, serializer);
          sse_encode_bool(plain, serializer);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiUnlockConstMeta,
        argValues: [seedWords, passphrase, network, server, plain, dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUnlockConstMeta => const TaskConstMeta(
    debugName: "unlock",
    argNames: [
      "seedWords",
      "passphrase",
      "network",
      "server",
      "plain",
      "dataDir",
    ],
  );

  @override
  AddressCheck crateApiValidateAddress({
    required NetworkId network,
    required String address,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_network_id(network, serializer);
          sse_encode_String(address, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_address_check,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiValidateAddressConstMeta,
        argValues: [network, address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiValidateAddressConstMeta => const TaskConstMeta(
    debugName: "validate_address",
    argNames: ["network", "address"],
  );

  @override
  Future<List<VaultSummary>> crateApiVaults() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_vault_summary,
          decodeErrorData: sse_decode_yew_error,
        ),
        constMeta: kCrateApiVaultsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultsConstMeta =>
      const TaskConstMeta(debugName: "vaults", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<SyncEvent> dco_decode_StreamSink_sync_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AddressCheck dco_decode_address_check(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AddressCheck(
      valid: dco_decode_bool(arr[0]),
      kind: dco_decode_String(arr[1]),
      yellowbackForm: dco_decode_bool(arr[2]),
      message: dco_decode_String(arr[3]),
    );
  }

  @protected
  AddressPair dco_decode_address_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AddressPair(
      ye: dco_decode_String(arr[0]),
      s: dco_decode_String(arr[1]),
      path: dco_decode_String(arr[2]),
      coveredBySeed: dco_decode_bool(arr[3]),
    );
  }

  @protected
  Balances dco_decode_balances(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return Balances(
      yecZat: dco_decode_i_64(arr[0]),
      yecReservedZat: dco_decode_i_64(arr[1]),
      yecPendingZat: dco_decode_i_64(arr[2]),
      yedCents: dco_decode_i_64(arr[3]),
      yedPendingCents: dco_decode_i_64(arr[4]),
      priceMicroUsd: dco_decode_opt_box_autoadd_i_64(arr[5]),
      heldCount: dco_decode_i_64(arr[6]),
      syncHeight: dco_decode_i_64(arr[7]),
      yedSendMinZat: dco_decode_i_64(arr[8]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  Created dco_decode_created(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Created(
      walletId: dco_decode_String(arr[0]),
      seedWords: dco_decode_opt_String(arr[1]),
      addressYe: dco_decode_String(arr[2]),
    );
  }

  @protected
  DryRun dco_decode_dry_run(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return DryRun(
      valid: dco_decode_bool(arr[0]),
      verdict: dco_decode_String(arr[1]),
      burnedCents: dco_decode_i_64(arr[2]),
      wouldBeRejected: dco_decode_bool(arr[3]),
      yedInCents: dco_decode_i_64(arr[4]),
      yedOutCents: dco_decode_i_64(arr[5]),
      accepted: dco_decode_bool(arr[6]),
    );
  }

  @protected
  ErrorKind dco_decode_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ErrorKind.values[raw as int];
  }

  @protected
  HistoryItem dco_decode_history_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return HistoryItem(
      txid: dco_decode_String(arr[0]),
      height: dco_decode_i_64(arr[1]),
      pending: dco_decode_bool(arr[2]),
      yecDeltaZat: dco_decode_i_64(arr[3]),
      yedDeltaCents: dco_decode_i_64(arr[4]),
      label: dco_decode_String(arr[5]),
      verdict: dco_decode_String(arr[6]),
      kind: dco_decode_String(arr[7]),
      hasPayload: dco_decode_bool(arr[8]),
      shielded: dco_decode_bool(arr[9]),
    );
  }

  @protected
  HistoryPage dco_decode_history_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HistoryPage(
      rows: dco_decode_list_history_item(arr[0]),
      page: dco_decode_u_32(arr[1]),
      total: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<AddressPair> dco_decode_list_address_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_address_pair).toList();
  }

  @protected
  List<HistoryItem> dco_decode_list_history_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_history_item).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Recipient> dco_decode_list_recipient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_recipient).toList();
  }

  @protected
  List<VaultSummary> dco_decode_list_vault_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_vault_summary).toList();
  }

  @protected
  MintEstimate dco_decode_mint_estimate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MintEstimate(
      cents: dco_decode_i_64(arr[0]),
      collateralZat: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  MintState dco_decode_mint_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MintState(
      mintId: dco_decode_String(arr[0]),
      state: dco_decode_String(arr[1]),
    );
  }

  @protected
  NetworkId dco_decode_network_id(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NetworkId.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  Recipient dco_decode_recipient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Recipient(
      address: dco_decode_String(arr[0]),
      cents: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  SendResult dco_decode_send_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SendResult(
      txid: dco_decode_String(arr[0]),
      verdict: dco_decode_String(arr[1]),
    );
  }

  @protected
  ServerProbe dco_decode_server_probe(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ServerProbe(
      serverVersion: dco_decode_String(arr[0]),
      chainName: dco_decode_String(arr[1]),
      tip: dco_decode_i_64(arr[2]),
      taddrSupport: dco_decode_bool(arr[3]),
      yellowback: dco_decode_yellowback_status(arr[4]),
    );
  }

  @protected
  Status dco_decode_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return Status(
      walletId: dco_decode_String(arr[0]),
      network: dco_decode_network_id(arr[1]),
      server: dco_decode_String(arr[2]),
      plain: dco_decode_bool(arr[3]),
      serverVersion: dco_decode_String(arr[4]),
      chainName: dco_decode_String(arr[5]),
      branchId: dco_decode_String(arr[6]),
      tip: dco_decode_i_64(arr[7]),
      birthday: dco_decode_i_64(arr[8]),
      syncHeight: dco_decode_i_64(arr[9]),
      addresses: dco_decode_i_64(arr[10]),
      yellowback: dco_decode_yellowback_status(arr[11]),
      coreVersion: dco_decode_String(arr[12]),
    );
  }

  @protected
  SyncEvent dco_decode_sync_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SyncEvent(
      stage: dco_decode_sync_stage(arr[0]),
      message: dco_decode_String(arr[1]),
      tip: dco_decode_i_64(arr[2]),
      syncHeight: dco_decode_i_64(arr[3]),
      yellowbackUsable: dco_decode_bool(arr[4]),
    );
  }

  @protected
  SyncStage dco_decode_sync_stage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncStage.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VaultSummary dco_decode_vault_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return VaultSummary(
      vaultTxid: dco_decode_String(arr[0]),
      cents: dco_decode_i_64(arr[1]),
      collateralZat: dco_decode_i_64(arr[2]),
      lockHeight: dco_decode_i_64(arr[3]),
      status: dco_decode_String(arr[4]),
    );
  }

  @protected
  WifExport dco_decode_wif_export(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WifExport(
      addressYe: dco_decode_String(arr[0]),
      addressS: dco_decode_String(arr[1]),
      wif: dco_decode_String(arr[2]),
      coveredBySeed: dco_decode_bool(arr[3]),
    );
  }

  @protected
  YecPreview dco_decode_yec_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return YecPreview(
      previewId: dco_decode_String(arr[0]),
      to: dco_decode_String(arr[1]),
      amountZat: dco_decode_i_64(arr[2]),
      amountBumped: dco_decode_bool(arr[3]),
      feeZat: dco_decode_i_64(arr[4]),
      changeZat: dco_decode_i_64(arr[5]),
      inputs: dco_decode_u_32(arr[6]),
      usesReserve: dco_decode_bool(arr[7]),
      keepsReservedZat: dco_decode_i_64(arr[8]),
      expiryHeight: dco_decode_u_32(arr[9]),
      txid: dco_decode_String(arr[10]),
    );
  }

  @protected
  YedPreview dco_decode_yed_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return YedPreview(
      previewId: dco_decode_String(arr[0]),
      recipients: dco_decode_list_recipient(arr[1]),
      totalCents: dco_decode_i_64(arr[2]),
      stage: dco_decode_String(arr[3]),
      yedInputs: dco_decode_u_32(arr[4]),
      changeCents: dco_decode_i_64(arr[5]),
      yecInputs: dco_decode_u_32(arr[6]),
      feeZat: dco_decode_i_64(arr[7]),
      yecChangeZat: dco_decode_i_64(arr[8]),
      expiryHeight: dco_decode_u_32(arr[9]),
      txid: dco_decode_String(arr[10]),
      dryRun: dco_decode_dry_run(arr[11]),
    );
  }

  @protected
  YellowbackStatus dco_decode_yellowback_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return YellowbackStatus(
      present: dco_decode_bool(arr[0]),
      usable: dco_decode_bool(arr[1]),
      rpcversion: dco_decode_i_64(arr[2]),
      enabled: dco_decode_bool(arr[3]),
      active: dco_decode_bool(arr[4]),
      serverVersion: dco_decode_String(arr[5]),
      feeZat: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  YewError dco_decode_yew_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return YewError(
      kind: dco_decode_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<SyncEvent> sse_decode_StreamSink_sync_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AddressCheck sse_decode_address_check(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_valid = sse_decode_bool(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_yellowbackForm = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    return AddressCheck(
      valid: var_valid,
      kind: var_kind,
      yellowbackForm: var_yellowbackForm,
      message: var_message,
    );
  }

  @protected
  AddressPair sse_decode_address_pair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ye = sse_decode_String(deserializer);
    var var_s = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_coveredBySeed = sse_decode_bool(deserializer);
    return AddressPair(
      ye: var_ye,
      s: var_s,
      path: var_path,
      coveredBySeed: var_coveredBySeed,
    );
  }

  @protected
  Balances sse_decode_balances(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_yecZat = sse_decode_i_64(deserializer);
    var var_yecReservedZat = sse_decode_i_64(deserializer);
    var var_yecPendingZat = sse_decode_i_64(deserializer);
    var var_yedCents = sse_decode_i_64(deserializer);
    var var_yedPendingCents = sse_decode_i_64(deserializer);
    var var_priceMicroUsd = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_heldCount = sse_decode_i_64(deserializer);
    var var_syncHeight = sse_decode_i_64(deserializer);
    var var_yedSendMinZat = sse_decode_i_64(deserializer);
    return Balances(
      yecZat: var_yecZat,
      yecReservedZat: var_yecReservedZat,
      yecPendingZat: var_yecPendingZat,
      yedCents: var_yedCents,
      yedPendingCents: var_yedPendingCents,
      priceMicroUsd: var_priceMicroUsd,
      heldCount: var_heldCount,
      syncHeight: var_syncHeight,
      yedSendMinZat: var_yedSendMinZat,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  Created sse_decode_created(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_walletId = sse_decode_String(deserializer);
    var var_seedWords = sse_decode_opt_String(deserializer);
    var var_addressYe = sse_decode_String(deserializer);
    return Created(
      walletId: var_walletId,
      seedWords: var_seedWords,
      addressYe: var_addressYe,
    );
  }

  @protected
  DryRun sse_decode_dry_run(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_valid = sse_decode_bool(deserializer);
    var var_verdict = sse_decode_String(deserializer);
    var var_burnedCents = sse_decode_i_64(deserializer);
    var var_wouldBeRejected = sse_decode_bool(deserializer);
    var var_yedInCents = sse_decode_i_64(deserializer);
    var var_yedOutCents = sse_decode_i_64(deserializer);
    var var_accepted = sse_decode_bool(deserializer);
    return DryRun(
      valid: var_valid,
      verdict: var_verdict,
      burnedCents: var_burnedCents,
      wouldBeRejected: var_wouldBeRejected,
      yedInCents: var_yedInCents,
      yedOutCents: var_yedOutCents,
      accepted: var_accepted,
    );
  }

  @protected
  ErrorKind sse_decode_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ErrorKind.values[inner];
  }

  @protected
  HistoryItem sse_decode_history_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txid = sse_decode_String(deserializer);
    var var_height = sse_decode_i_64(deserializer);
    var var_pending = sse_decode_bool(deserializer);
    var var_yecDeltaZat = sse_decode_i_64(deserializer);
    var var_yedDeltaCents = sse_decode_i_64(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_verdict = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_hasPayload = sse_decode_bool(deserializer);
    var var_shielded = sse_decode_bool(deserializer);
    return HistoryItem(
      txid: var_txid,
      height: var_height,
      pending: var_pending,
      yecDeltaZat: var_yecDeltaZat,
      yedDeltaCents: var_yedDeltaCents,
      label: var_label,
      verdict: var_verdict,
      kind: var_kind,
      hasPayload: var_hasPayload,
      shielded: var_shielded,
    );
  }

  @protected
  HistoryPage sse_decode_history_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rows = sse_decode_list_history_item(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    var var_total = sse_decode_i_64(deserializer);
    return HistoryPage(rows: var_rows, page: var_page, total: var_total);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<AddressPair> sse_decode_list_address_pair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AddressPair>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_address_pair(deserializer));
    }
    return ans_;
  }

  @protected
  List<HistoryItem> sse_decode_list_history_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HistoryItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_history_item(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Recipient> sse_decode_list_recipient(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Recipient>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_recipient(deserializer));
    }
    return ans_;
  }

  @protected
  List<VaultSummary> sse_decode_list_vault_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VaultSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_vault_summary(deserializer));
    }
    return ans_;
  }

  @protected
  MintEstimate sse_decode_mint_estimate(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cents = sse_decode_i_64(deserializer);
    var var_collateralZat = sse_decode_i_64(deserializer);
    return MintEstimate(cents: var_cents, collateralZat: var_collateralZat);
  }

  @protected
  MintState sse_decode_mint_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mintId = sse_decode_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    return MintState(mintId: var_mintId, state: var_state);
  }

  @protected
  NetworkId sse_decode_network_id(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return NetworkId.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Recipient sse_decode_recipient(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_cents = sse_decode_i_64(deserializer);
    return Recipient(address: var_address, cents: var_cents);
  }

  @protected
  SendResult sse_decode_send_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txid = sse_decode_String(deserializer);
    var var_verdict = sse_decode_String(deserializer);
    return SendResult(txid: var_txid, verdict: var_verdict);
  }

  @protected
  ServerProbe sse_decode_server_probe(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_serverVersion = sse_decode_String(deserializer);
    var var_chainName = sse_decode_String(deserializer);
    var var_tip = sse_decode_i_64(deserializer);
    var var_taddrSupport = sse_decode_bool(deserializer);
    var var_yellowback = sse_decode_yellowback_status(deserializer);
    return ServerProbe(
      serverVersion: var_serverVersion,
      chainName: var_chainName,
      tip: var_tip,
      taddrSupport: var_taddrSupport,
      yellowback: var_yellowback,
    );
  }

  @protected
  Status sse_decode_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_walletId = sse_decode_String(deserializer);
    var var_network = sse_decode_network_id(deserializer);
    var var_server = sse_decode_String(deserializer);
    var var_plain = sse_decode_bool(deserializer);
    var var_serverVersion = sse_decode_String(deserializer);
    var var_chainName = sse_decode_String(deserializer);
    var var_branchId = sse_decode_String(deserializer);
    var var_tip = sse_decode_i_64(deserializer);
    var var_birthday = sse_decode_i_64(deserializer);
    var var_syncHeight = sse_decode_i_64(deserializer);
    var var_addresses = sse_decode_i_64(deserializer);
    var var_yellowback = sse_decode_yellowback_status(deserializer);
    var var_coreVersion = sse_decode_String(deserializer);
    return Status(
      walletId: var_walletId,
      network: var_network,
      server: var_server,
      plain: var_plain,
      serverVersion: var_serverVersion,
      chainName: var_chainName,
      branchId: var_branchId,
      tip: var_tip,
      birthday: var_birthday,
      syncHeight: var_syncHeight,
      addresses: var_addresses,
      yellowback: var_yellowback,
      coreVersion: var_coreVersion,
    );
  }

  @protected
  SyncEvent sse_decode_sync_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stage = sse_decode_sync_stage(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_tip = sse_decode_i_64(deserializer);
    var var_syncHeight = sse_decode_i_64(deserializer);
    var var_yellowbackUsable = sse_decode_bool(deserializer);
    return SyncEvent(
      stage: var_stage,
      message: var_message,
      tip: var_tip,
      syncHeight: var_syncHeight,
      yellowbackUsable: var_yellowbackUsable,
    );
  }

  @protected
  SyncStage sse_decode_sync_stage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SyncStage.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VaultSummary sse_decode_vault_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_vaultTxid = sse_decode_String(deserializer);
    var var_cents = sse_decode_i_64(deserializer);
    var var_collateralZat = sse_decode_i_64(deserializer);
    var var_lockHeight = sse_decode_i_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    return VaultSummary(
      vaultTxid: var_vaultTxid,
      cents: var_cents,
      collateralZat: var_collateralZat,
      lockHeight: var_lockHeight,
      status: var_status,
    );
  }

  @protected
  WifExport sse_decode_wif_export(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_addressYe = sse_decode_String(deserializer);
    var var_addressS = sse_decode_String(deserializer);
    var var_wif = sse_decode_String(deserializer);
    var var_coveredBySeed = sse_decode_bool(deserializer);
    return WifExport(
      addressYe: var_addressYe,
      addressS: var_addressS,
      wif: var_wif,
      coveredBySeed: var_coveredBySeed,
    );
  }

  @protected
  YecPreview sse_decode_yec_preview(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_previewId = sse_decode_String(deserializer);
    var var_to = sse_decode_String(deserializer);
    var var_amountZat = sse_decode_i_64(deserializer);
    var var_amountBumped = sse_decode_bool(deserializer);
    var var_feeZat = sse_decode_i_64(deserializer);
    var var_changeZat = sse_decode_i_64(deserializer);
    var var_inputs = sse_decode_u_32(deserializer);
    var var_usesReserve = sse_decode_bool(deserializer);
    var var_keepsReservedZat = sse_decode_i_64(deserializer);
    var var_expiryHeight = sse_decode_u_32(deserializer);
    var var_txid = sse_decode_String(deserializer);
    return YecPreview(
      previewId: var_previewId,
      to: var_to,
      amountZat: var_amountZat,
      amountBumped: var_amountBumped,
      feeZat: var_feeZat,
      changeZat: var_changeZat,
      inputs: var_inputs,
      usesReserve: var_usesReserve,
      keepsReservedZat: var_keepsReservedZat,
      expiryHeight: var_expiryHeight,
      txid: var_txid,
    );
  }

  @protected
  YedPreview sse_decode_yed_preview(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_previewId = sse_decode_String(deserializer);
    var var_recipients = sse_decode_list_recipient(deserializer);
    var var_totalCents = sse_decode_i_64(deserializer);
    var var_stage = sse_decode_String(deserializer);
    var var_yedInputs = sse_decode_u_32(deserializer);
    var var_changeCents = sse_decode_i_64(deserializer);
    var var_yecInputs = sse_decode_u_32(deserializer);
    var var_feeZat = sse_decode_i_64(deserializer);
    var var_yecChangeZat = sse_decode_i_64(deserializer);
    var var_expiryHeight = sse_decode_u_32(deserializer);
    var var_txid = sse_decode_String(deserializer);
    var var_dryRun = sse_decode_dry_run(deserializer);
    return YedPreview(
      previewId: var_previewId,
      recipients: var_recipients,
      totalCents: var_totalCents,
      stage: var_stage,
      yedInputs: var_yedInputs,
      changeCents: var_changeCents,
      yecInputs: var_yecInputs,
      feeZat: var_feeZat,
      yecChangeZat: var_yecChangeZat,
      expiryHeight: var_expiryHeight,
      txid: var_txid,
      dryRun: var_dryRun,
    );
  }

  @protected
  YellowbackStatus sse_decode_yellowback_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_present = sse_decode_bool(deserializer);
    var var_usable = sse_decode_bool(deserializer);
    var var_rpcversion = sse_decode_i_64(deserializer);
    var var_enabled = sse_decode_bool(deserializer);
    var var_active = sse_decode_bool(deserializer);
    var var_serverVersion = sse_decode_String(deserializer);
    var var_feeZat = sse_decode_i_64(deserializer);
    return YellowbackStatus(
      present: var_present,
      usable: var_usable,
      rpcversion: var_rpcversion,
      enabled: var_enabled,
      active: var_active,
      serverVersion: var_serverVersion,
      feeZat: var_feeZat,
    );
  }

  @protected
  YewError sse_decode_yew_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    return YewError(kind: var_kind, message: var_message);
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_sync_event_Sse(
    RustStreamSink<SyncEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_address_check(AddressCheck self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.valid, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_bool(self.yellowbackForm, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_address_pair(AddressPair self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ye, serializer);
    sse_encode_String(self.s, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.coveredBySeed, serializer);
  }

  @protected
  void sse_encode_balances(Balances self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.yecZat, serializer);
    sse_encode_i_64(self.yecReservedZat, serializer);
    sse_encode_i_64(self.yecPendingZat, serializer);
    sse_encode_i_64(self.yedCents, serializer);
    sse_encode_i_64(self.yedPendingCents, serializer);
    sse_encode_opt_box_autoadd_i_64(self.priceMicroUsd, serializer);
    sse_encode_i_64(self.heldCount, serializer);
    sse_encode_i_64(self.syncHeight, serializer);
    sse_encode_i_64(self.yedSendMinZat, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_created(Created self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.walletId, serializer);
    sse_encode_opt_String(self.seedWords, serializer);
    sse_encode_String(self.addressYe, serializer);
  }

  @protected
  void sse_encode_dry_run(DryRun self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.valid, serializer);
    sse_encode_String(self.verdict, serializer);
    sse_encode_i_64(self.burnedCents, serializer);
    sse_encode_bool(self.wouldBeRejected, serializer);
    sse_encode_i_64(self.yedInCents, serializer);
    sse_encode_i_64(self.yedOutCents, serializer);
    sse_encode_bool(self.accepted, serializer);
  }

  @protected
  void sse_encode_error_kind(ErrorKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_history_item(HistoryItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.txid, serializer);
    sse_encode_i_64(self.height, serializer);
    sse_encode_bool(self.pending, serializer);
    sse_encode_i_64(self.yecDeltaZat, serializer);
    sse_encode_i_64(self.yedDeltaCents, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.verdict, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_bool(self.hasPayload, serializer);
    sse_encode_bool(self.shielded, serializer);
  }

  @protected
  void sse_encode_history_page(HistoryPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_history_item(self.rows, serializer);
    sse_encode_u_32(self.page, serializer);
    sse_encode_i_64(self.total, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_address_pair(
    List<AddressPair> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_address_pair(item, serializer);
    }
  }

  @protected
  void sse_encode_list_history_item(
    List<HistoryItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_history_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_recipient(
    List<Recipient> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_recipient(item, serializer);
    }
  }

  @protected
  void sse_encode_list_vault_summary(
    List<VaultSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_vault_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_mint_estimate(MintEstimate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.cents, serializer);
    sse_encode_i_64(self.collateralZat, serializer);
  }

  @protected
  void sse_encode_mint_state(MintState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mintId, serializer);
    sse_encode_String(self.state, serializer);
  }

  @protected
  void sse_encode_network_id(NetworkId self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_recipient(Recipient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_i_64(self.cents, serializer);
  }

  @protected
  void sse_encode_send_result(SendResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.txid, serializer);
    sse_encode_String(self.verdict, serializer);
  }

  @protected
  void sse_encode_server_probe(ServerProbe self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.serverVersion, serializer);
    sse_encode_String(self.chainName, serializer);
    sse_encode_i_64(self.tip, serializer);
    sse_encode_bool(self.taddrSupport, serializer);
    sse_encode_yellowback_status(self.yellowback, serializer);
  }

  @protected
  void sse_encode_status(Status self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.walletId, serializer);
    sse_encode_network_id(self.network, serializer);
    sse_encode_String(self.server, serializer);
    sse_encode_bool(self.plain, serializer);
    sse_encode_String(self.serverVersion, serializer);
    sse_encode_String(self.chainName, serializer);
    sse_encode_String(self.branchId, serializer);
    sse_encode_i_64(self.tip, serializer);
    sse_encode_i_64(self.birthday, serializer);
    sse_encode_i_64(self.syncHeight, serializer);
    sse_encode_i_64(self.addresses, serializer);
    sse_encode_yellowback_status(self.yellowback, serializer);
    sse_encode_String(self.coreVersion, serializer);
  }

  @protected
  void sse_encode_sync_event(SyncEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sync_stage(self.stage, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_i_64(self.tip, serializer);
    sse_encode_i_64(self.syncHeight, serializer);
    sse_encode_bool(self.yellowbackUsable, serializer);
  }

  @protected
  void sse_encode_sync_stage(SyncStage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vault_summary(VaultSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.vaultTxid, serializer);
    sse_encode_i_64(self.cents, serializer);
    sse_encode_i_64(self.collateralZat, serializer);
    sse_encode_i_64(self.lockHeight, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_wif_export(WifExport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.addressYe, serializer);
    sse_encode_String(self.addressS, serializer);
    sse_encode_String(self.wif, serializer);
    sse_encode_bool(self.coveredBySeed, serializer);
  }

  @protected
  void sse_encode_yec_preview(YecPreview self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.previewId, serializer);
    sse_encode_String(self.to, serializer);
    sse_encode_i_64(self.amountZat, serializer);
    sse_encode_bool(self.amountBumped, serializer);
    sse_encode_i_64(self.feeZat, serializer);
    sse_encode_i_64(self.changeZat, serializer);
    sse_encode_u_32(self.inputs, serializer);
    sse_encode_bool(self.usesReserve, serializer);
    sse_encode_i_64(self.keepsReservedZat, serializer);
    sse_encode_u_32(self.expiryHeight, serializer);
    sse_encode_String(self.txid, serializer);
  }

  @protected
  void sse_encode_yed_preview(YedPreview self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.previewId, serializer);
    sse_encode_list_recipient(self.recipients, serializer);
    sse_encode_i_64(self.totalCents, serializer);
    sse_encode_String(self.stage, serializer);
    sse_encode_u_32(self.yedInputs, serializer);
    sse_encode_i_64(self.changeCents, serializer);
    sse_encode_u_32(self.yecInputs, serializer);
    sse_encode_i_64(self.feeZat, serializer);
    sse_encode_i_64(self.yecChangeZat, serializer);
    sse_encode_u_32(self.expiryHeight, serializer);
    sse_encode_String(self.txid, serializer);
    sse_encode_dry_run(self.dryRun, serializer);
  }

  @protected
  void sse_encode_yellowback_status(
    YellowbackStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.present, serializer);
    sse_encode_bool(self.usable, serializer);
    sse_encode_i_64(self.rpcversion, serializer);
    sse_encode_bool(self.enabled, serializer);
    sse_encode_bool(self.active, serializer);
    sse_encode_String(self.serverVersion, serializer);
    sse_encode_i_64(self.feeZat, serializer);
  }

  @protected
  void sse_encode_yew_error(YewError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
  }
}
