//! gRPC clients (D-W-4): `CompactTxStreamer` (the untouched transparent path) and
//! `YellowbackStreamer` (the Yellowback relay), generated by `build.rs` from `../proto/`, which
//! is pinned to `lightwalletd-dd` (`proto/PIN`). TLS via `rustls` (`tls.rs`).
//!
//! `compact.rs` is the typed T0 wrapper (Phase W1); `yellowback.rs` comes in W2.

use thiserror::Error;

/// The generated protobuf messages and gRPC client stubs, package `cash.z.wallet.sdk.rpc`.
#[allow(clippy::all, clippy::pedantic, missing_docs)]
pub mod rpc {
    tonic::include_proto!("cash.z.wallet.sdk.rpc");
}

pub mod compact;
pub mod tls;

pub use compact::{CompactClient, LightdInfo, Utxo as ServerUtxo};
pub use rpc::compact_tx_streamer_client::CompactTxStreamerClient;
pub use rpc::yellowback_streamer_client::YellowbackStreamerClient;
pub use tls::Server;

/// Network errors.
#[derive(Debug, Error)]
pub enum NetError {
    /// The endpoint could not be built.
    #[error("server config: {0}")]
    Config(String),
    /// Transport (connect, TLS) failure.
    #[error("transport: {0}")]
    Transport(#[from] tonic::transport::Error),
    /// A gRPC status from the server.
    #[error("rpc {}: {}", .0.code(), .0.message())]
    Status(#[from] tonic::Status),
    /// The server answered but not for this build (chain name, `taddrSupport`, branch id).
    #[error("server mismatch: {0}")]
    Mismatch(String),
    /// `SendTransaction` returned a non-zero error code.
    #[error("send rejected ({code}): {message}")]
    SendRejected {
        /// `SendResponse.errorCode`.
        code: i32,
        /// `SendResponse.errorMessage`.
        message: String,
    },
}

#[cfg(test)]
mod tests {
    use super::rpc;

    #[test]
    fn both_services_are_generated() {
        // Compile-time proof that the two client types exist over a `tonic::transport::Channel`.
        fn _compact(
            c: tonic::transport::Channel,
        ) -> super::CompactTxStreamerClient<tonic::transport::Channel> {
            super::CompactTxStreamerClient::new(c)
        }
        fn _yellowback(
            c: tonic::transport::Channel,
        ) -> super::YellowbackStreamerClient<tonic::transport::Channel> {
            super::YellowbackStreamerClient::new(c)
        }
        let info = rpc::LightdInfo::default();
        assert_eq!(info.chain_name, "");
    }
}
