//! gRPC clients (D-W-4): `CompactTxStreamer` (the untouched transparent path) and
//! `YellowbackStreamer` (the Yellowback relay), generated by `build.rs` from `../proto/`, which
//! is pinned to `lightwalletd-dd` (`proto/PIN`). TLS via `rustls` (`tls.rs`, Phase W1).
//!
//! `compact.rs` and `yellowback.rs` (the typed wrappers over the raw clients) come in W1/W2.

/// The generated protobuf messages and gRPC client stubs, package `cash.z.wallet.sdk.rpc`.
#[allow(clippy::all, clippy::pedantic, missing_docs)]
pub mod rpc {
    tonic::include_proto!("cash.z.wallet.sdk.rpc");
}

pub use rpc::compact_tx_streamer_client::CompactTxStreamerClient;
pub use rpc::yellowback_streamer_client::YellowbackStreamerClient;

#[cfg(test)]
mod tests {
    use super::rpc;

    #[test]
    fn both_services_are_generated() {
        // Compile-time proof that the two client types exist over a `tonic::transport::Channel`.
        fn _compact(
            c: tonic::transport::Channel,
        ) -> super::CompactTxStreamerClient<tonic::transport::Channel> {
            super::CompactTxStreamerClient::new(c)
        }
        fn _yellowback(
            c: tonic::transport::Channel,
        ) -> super::YellowbackStreamerClient<tonic::transport::Channel> {
            super::YellowbackStreamerClient::new(c)
        }
        let info = rpc::LightdInfo::default();
        assert_eq!(info.chain_name, "");
    }
}
