// Copyright (c) 2026 The Ycash developers
// Distributed under the MIT software license, see the accompanying
// file LICENSE or https://www.opensource.org/licenses/mit-license.php .

//! gRPC clients (D-W-4): `CompactTxStreamer` (the untouched transparent path) and
//! `YellowbackStreamer` (the Yellowback relay), generated by `build.rs` from `../proto/`, which
//! is pinned to `lightwalletd-dd` (`proto/PIN`). TLS via `rustls` (`tls.rs`).
//!
//! `compact.rs` is the typed T0 wrapper (Phase W1); `yellowback.rs` the typed T1–T3 wrapper
//! with contract rule 1 (`probe`) and the node-error mapping (Phase W2).

use thiserror::Error;

/// The generated protobuf messages and gRPC client stubs, package `cash.z.wallet.sdk.rpc`.
#[allow(clippy::all, clippy::pedantic, missing_docs)]
pub mod rpc {
    tonic::include_proto!("cash.z.wallet.sdk.rpc");
}

pub mod compact;
pub mod tls;
pub mod yellowback;

pub use compact::{CompactClient, LightdInfo, Utxo as ServerUtxo};
pub use rpc::compact_tx_streamer_client::CompactTxStreamerClient;
pub use rpc::yellowback_streamer_client::YellowbackStreamerClient;
pub use tls::{default_servers, DefaultServer, Server};
pub use yellowback::{Availability, Token, Validation, YellowbackClient};

/// Upper bounds on what one call collects from a server stream (audit G-7): the chosen server
/// can lie, but it must not be able to grow the wallet's memory without bound. Each is far
/// above any honest answer; a reply past the bound is [`NetError::TooLarge`] and the sync
/// fails with that error instead of the process being killed.
pub mod limits {
    /// `GetAddressUtxos`: entries over all own addresses.
    pub const MAX_UTXOS: usize = 100_000;
    /// `GetTaddressTxids`: transactions per address and range.
    pub const MAX_TXS_PER_ADDRESS: usize = 50_000;
    /// `GetTaddressTxids`: raw bytes per address and range (64 MiB).
    pub const MAX_TX_BYTES_PER_ADDRESS: usize = 64 << 20;
    /// `GetAddressTokens`: tokens over all own addresses.
    pub const MAX_TOKENS: usize = 100_000;
    /// `ListVaults`, `ListClaimable`.
    pub const MAX_VAULTS: usize = 10_000;
    /// `GetAttestations`.
    pub const MAX_ATTESTATIONS: usize = 10_000;
    /// `ListAttestors` (`N_SLOTS` is 9).
    pub const MAX_ATTESTORS: usize = 1_000;
}

/// An error's message followed by every source in its chain, `: `-joined.
fn with_sources(e: &dyn std::error::Error) -> String {
    let mut s = e.to_string();
    let mut cur = e.source();
    while let Some(src) = cur {
        s.push_str(": ");
        s.push_str(&src.to_string());
        cur = src.source();
    }
    s
}

/// Network errors.
#[derive(Debug, Error)]
pub enum NetError {
    /// The endpoint could not be built.
    #[error("server config: {0}")]
    Config(String),
    /// Transport (connect, TLS) failure. `tonic::transport::Error` displays as the bare
    /// "transport error"; the cause (connection refused, TLS, DNS) is in its source chain, so the
    /// message walks it (W6: the app shows this verbatim).
    #[error("transport: {}", with_sources(.0))]
    Transport(#[from] tonic::transport::Error),
    /// A gRPC status from the server.
    #[error("rpc {}: {}", .0.code(), .0.message())]
    Status(#[from] tonic::Status),
    /// The server answered but not for this build (chain name, `taddrSupport`, branch id).
    #[error("server mismatch: {0}")]
    Mismatch(String),
    /// `SendTransaction` returned a non-zero error code.
    #[error("send rejected ({code}): {message}")]
    SendRejected {
        /// `SendResponse.errorCode`.
        code: i32,
        /// `SendResponse.errorMessage`.
        message: String,
    },
    /// The server does not offer `YellowbackStreamer` (`UNIMPLEMENTED`; contract rule 1).
    #[error("the server offers no Yellowback service (UNIMPLEMENTED)")]
    Unimplemented,
    /// The node's `rpcversion` is not the one this build implements (contract rule 1).
    #[error("unknown Yellowback rpcversion {0} (this build implements {known})", known = yellowback::KNOWN_RPCVERSION)]
    UnknownRpcVersion(i64),
    /// A stream exceeded its bound ([`limits`]): the server answered more than any honest
    /// server would.
    #[error("the server sent more than {limit} {what}; refusing the answer (try another server)")]
    TooLarge {
        /// What was being collected.
        what: &'static str,
        /// The bound.
        limit: usize,
    },
    /// The node refused a `yed_*` RPC (`FAILED_PRECONDITION`): `identifier` is the contract's
    /// error identifier (`change-floor`, `tx-not-found`, …), `message` the node's text verbatim.
    #[error("node: {message}")]
    Node {
        /// The identifier before the first colon.
        identifier: String,
        /// The whole message.
        message: String,
    },
}

#[cfg(test)]
mod tests {
    use super::rpc;

    #[test]
    fn both_services_are_generated() {
        // Compile-time proof that the two client types exist over a `tonic::transport::Channel`.
        fn _compact(
            c: tonic::transport::Channel,
        ) -> super::CompactTxStreamerClient<tonic::transport::Channel> {
            super::CompactTxStreamerClient::new(c)
        }
        fn _yellowback(
            c: tonic::transport::Channel,
        ) -> super::YellowbackStreamerClient<tonic::transport::Channel> {
            super::YellowbackStreamerClient::new(c)
        }
        let info = rpc::LightdInfo::default();
        assert_eq!(info.chain_name, "");
    }
}
