#!/usr/bin/env bash
# Builds yew-core for iOS device and simulator and packages app/ios/Frameworks/YewCore.xcframework.
# Idempotent: re-running rebuilds only what cargo decides and replaces the xcframework.
# Requires: rustup targets aarch64-apple-ios + aarch64-apple-ios-sim, Xcode (xcodebuild), protoc.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$here"
need() { command -v "$1" >/dev/null 2>&1 || { echo "build-core-ios: missing '$1'. $2" >&2; exit 1; }; }
need cargo "Install Rust: https://rustup.rs (the version is in rust-toolchain.toml)"
need protoc "Install protobuf: brew install protobuf"
need xcodebuild "Install Xcode from the App Store, then: sudo xcode-select -s /Applications/Xcode.app"
[[ "$(uname -s)" == "Darwin" ]] || { echo "build-core-ios: macOS only" >&2; exit 1; }
targets=(aarch64-apple-ios aarch64-apple-ios-sim)
for t in "${targets[@]}"; do
  rustup target list --installed | grep -qx "$t" || rustup target add "$t"
done
profile="${PROFILE:-release}"
flag=(); [[ "$profile" == "release" ]] && flag=(--release)
for t in "${targets[@]}"; do
  cargo build -p yew-core --lib --target "$t" "${flag[@]}"
done
tdir="${CARGO_TARGET_DIR:-$here/target}"
out="$here/app/ios/Frameworks/YewCore.xcframework"
hdr="$(mktemp -d)"
# Header: flutter_rust_bridge's generated C header when gen-bridge.sh has run; a stub otherwise.
if [[ -f "$here/core/include/yew_core.h" ]]; then cp "$here/core/include/yew_core.h" "$hdr/"; else
  printf '/* yew-core: header generated by scripts/gen-bridge.sh (Phase W3). */\n' > "$hdr/yew_core.h"; fi
rm -rf "$out"
mkdir -p "$(dirname "$out")"
xcodebuild -create-xcframework \
  -library "$tdir/aarch64-apple-ios/$profile/libyew_core.a" -headers "$hdr" \
  -library "$tdir/aarch64-apple-ios-sim/$profile/libyew_core.a" -headers "$hdr" \
  -output "$out"
rm -rf "$hdr"
echo "build-core-ios: wrote $out"
